import React,{useEffect,useMemo,useState} from "react";
import { pledgesService,pledgeAssetTypes,pledgeStatuses } from "../../services/pledges";

export const companyIdOf=(props={})=>props.currentCompany?.company_id||props.currentCompany?.id||props.currentUser?.company_id||"";
export const ErrorBox=({text})=>text?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{text}</div>:null;
export const Empty=()=> <div className="rounded-2xl border border-dashed p-8 text-center text-slate-400">لا توجد بيانات محفوظة بعد</div>;
export const Loading=()=> <div className="panel p-8 text-center font-bold text-slate-500">جاري تحميل البيانات...</div>;
export const PageTitle=({title,desc,children})=><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">{title}</h1>{desc&&<p className="mt-1 text-sm text-slate-500">{desc}</p>}</div>{children}</div>;
export const Money=({value})=><>{new Intl.NumberFormat("ar-SA",{maximumFractionDigits:2}).format(Number(value||0))} ر.س</>;
export const Risk=({value="عادي"})=><span className={"rounded-full px-3 py-1 text-xs font-bold "+(value==="مرتفع"?"bg-red-100 text-red-700":value==="متوسط"?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700")}>{value}</span>;
const handled="تعذر تحميل البيانات، يرجى مراجعة الإعدادات أو الاتصال.";
const PledgeField=({form={},name,label,type="text",required=false,onChange})=><label className="text-sm font-bold">{label}{required&&" *"}<input className="field mt-1" name={name} type={type} value={form[name]??""} onChange={e=>onChange(name,e.target.value)}/></label>;
const ValuationNumberField=({form={},name,label,onChange})=><label className="text-sm font-bold">{label}<input type="number" className="field mt-1" name={name} value={form[name]??""} onChange={e=>onChange(name,e.target.value)}/></label>;

const useLoad=(loader,deps=[])=>{
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const result=await loader();setRows(Array.isArray(result)?result:[])}catch(e){console.error("Pledges page load error",e);setRows([]);setError(handled)}finally{setLoading(false)}};
 useEffect(()=>{load()},deps);return{rows,loading,error,load,setRows};
};

export function PledgesDashboardPage(props={}){
 const companyId=companyIdOf(props),[stats,setStats]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{setLoading(true);try{const x=await pledgesService.getPledgesDashboardStats(companyId);if(active)setStats(x||{})}catch(e){console.error("Pledges dashboard error",e);if(active)setError(handled)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[companyId]);
 if(loading)return <Loading/>;const cards=[["إجمالي الرهون النشطة",stats.active_count],["إجمالي المبالغ المصروفة",<Money value={stats.approved_amount_total}/>],["إجمالي قيمة الأصول المرهونة",<Money value={stats.asset_value_total}/>],["المستحقة خلال 7 أيام",stats.due_soon_count],["الرهون المتأخرة",stats.overdue_count],["الرهون المفكوكة",stats.redeemed_count],["الأصول تحت التصفية",stats.liquidation_count],["نسبة المخاطر",`${stats.risk_percent||0}%`]];
 const status=Object.entries((stats.pledges||[]).reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{}));
 const types=Object.entries((stats.assets||[]).reduce((a,x)=>(a[x.asset_type]=(a[x.asset_type]||0)+1,a),{}));
 const branches=Object.entries((stats.pledges||[]).reduce((a,x)=>(a[x.branch||"غير محدد"]=(a[x.branch||"غير محدد"]||0)+1,a),{}));
 const Chart=({title,data})=><div className="panel p-5"><h3 className="mb-4 font-black">{title}</h3>{data.length?data.map(([k,v])=><div className="mb-3" key={k}><div className="mb-1 flex justify-between text-xs font-bold"><span>{k}</span><span>{v}</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-violet-700" style={{width:`${Math.max(8,Math.min(100,v/Math.max(...data.map(x=>x[1]))*100))}%`}}/></div></div>):<Empty/>}</div>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="لوحة الرهون" desc="ملخص تشغيلي للأصول المرهونة والاستحقاقات"/><ErrorBox text={error}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([a,b])=><div className="panel p-5" key={a}><p className="text-sm font-bold text-slate-500">{a}</p><b className="mt-2 block text-2xl text-violet-800">{b??0}</b></div>)}</div><div className="grid gap-5 lg:grid-cols-3"><Chart title="رهون حسب الحالة" data={status}/><Chart title="رهون حسب نوع الأصل" data={types}/><Chart title="رهون حسب الفرع" data={branches}/></div></div>;
}

const today=()=>new Date().toISOString().slice(0,10);
const preciousTypes=["ذهب","فضة","مجوهرات"];
const defaultForm={customer_name:"",identity_type:"هوية وطنية",identity_number:"",phone:"",address:"",risk_level:"عادي",asset_type:"ذهب",asset_name:"",asset_description:"",asset_model:"",serial_number:"",gold_weight:"",gold_karat:"21",gram_price:"",safety_discount_percent:10,quick_sale_value:"",condition_status:"جيد",accessories:"",ownership_proof:"",plate_no:"",chassis_no:"",manufacture_year:"",document_type:"",document_number:"",property_location:"",owner_name:"",estimated_market_value:"",accepted_pledge_value:"",financing_ratio:70,max_allowed_amount:"",vault_no:"",shelf_no:"",bag_no:"",pledge_no:"",branch:"",pledge_date:today(),due_date:"",requested_amount:"",approved_amount:"",total_fees:"",notes:""};

const AssetFields=({form={},set})=>{
 const precious=preciousTypes.includes(form.asset_type);
 const commonValue=Number(form.estimated_market_value||0);
 const accepted=precious?commonValue*(1-Number(form.safety_discount_percent||0)/100):Number(form.quick_sale_value||commonValue);
 const max=accepted*Number(form.financing_ratio||0)/100;
 const F=(name,label,type="text")=><PledgeField form={form} onChange={set} name={name} label={label} type={type}/>;
 return <div className="contents">
  {precious&&<>{F("gold_weight","الوزن","number")}{F("gold_karat","العيار")}{F("gram_price","سعر الجرام","number")}{F("safety_discount_percent","نسبة خصم الأمان","number")}</>}
  {form.asset_type==="جوال"&&<>{F("asset_name","اسم الجهاز")}{F("asset_model","الشركة / الموديل")}{F("serial_number","الرقم التسلسلي / IMEI")}{F("condition_status","الحالة")}{F("accessories","الملحقات")}{F("ownership_proof","إثبات الملكية")}</>}
  {form.asset_type==="سيارة"&&<>{F("asset_name","نوع السيارة")}{F("asset_model","الموديل")}{F("plate_no","رقم اللوحة")}{F("chassis_no","رقم الشاصي")}{F("manufacture_year","سنة الصنع","number")}{F("condition_status","الحالة")}{F("ownership_proof","وثيقة الملكية")}</>}
  {form.asset_type==="معدات"&&<>{F("asset_name","اسم المعدة")}{F("serial_number","الرقم التسلسلي")}{F("condition_status","الحالة")}{F("ownership_proof","إثبات الملكية")}</>}
  {form.asset_type==="وثيقة عقار"&&<>{F("document_type","نوع الوثيقة")}{F("document_number","رقم الوثيقة")}{F("property_location","موقع العقار")}{F("owner_name","اسم المالك")}{F("ownership_proof","إثبات الملكية")}</>}
  {form.asset_type==="أصل آخر"&&<>{F("asset_name","اسم الأصل")}{F("asset_description","وصف الأصل")}{F("serial_number","الرقم التسلسلي إن وجد")}{F("condition_status","الحالة")}{F("ownership_proof","إثبات الملكية")}</>}
  {!precious&&form.asset_type!=="وثيقة عقار"&&form.asset_type!=="أصل آخر"&&F("asset_description","وصف الأصل")}
  {precious&&<>{F("asset_name","اسم الأصل")}{F("asset_description","وصف الأصل")}{F("condition_status","الحالة")}{F("ownership_proof","إثبات الملكية")}</>}
  {F("estimated_market_value",form.asset_type==="وثيقة عقار"?"القيمة التقديرية":"القيمة السوقية","number")}
  {!precious&&F("quick_sale_value","قيمة البيع السريع","number")}
  {F("financing_ratio","نسبة التمويل","number")}
  <label className="text-sm font-bold">القيمة المقبولة للرهن<input className="field mt-1 bg-slate-50" readOnly value={Number(accepted||0).toFixed(2)}/></label>
  <label className="text-sm font-bold">أقصى مبلغ مسموح<input className="field mt-1 bg-slate-50" readOnly value={Number(max||0).toFixed(2)}/></label>
 </div>;
};

export function NewPledgePage(props={}){
 const companyId=companyIdOf(props),user=props.currentUser||{},[step,setStep]=useState(1),[form,setForm]=useState(defaultForm),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[errors,setErrors]=useState([]);
 const set=(name,value)=>setForm(prev=>({...prev,[name]:value}));
 const precious=preciousTypes.includes(form.asset_type);
 const market=precious&&form.gold_weight&&form.gram_price?Number(form.gold_weight)*Number(form.gram_price):Number(form.estimated_market_value||0);
 const accepted=precious?market*(1-Number(form.safety_discount_percent||0)/100):Number(form.quick_sale_value||market);
 const maximum=accepted*Number(form.financing_ratio||0)/100;
 const validate=()=>{const e=[];if(!String(form.customer_name||"").trim())e.push("اسم العميل مطلوب.");if(!String(form.identity_number||"").trim())e.push("رقم الهوية مطلوب.");if(!String(form.phone||"").trim())e.push("رقم الجوال مطلوب.");if(!form.asset_type)e.push("نوع الأصل مطلوب.");if(!String(form.asset_description||form.asset_name||form.document_type||"").trim())e.push("وصف الأصل أو اسمه مطلوب.");if(!form.pledge_date)e.push("تاريخ الرهن مطلوب.");if(!form.due_date)e.push("تاريخ الاستحقاق مطلوب.");if(form.pledge_date&&form.due_date&&form.due_date<=form.pledge_date)e.push("يجب أن يكون تاريخ الاستحقاق بعد تاريخ الرهن.");if(Number(form.approved_amount)>Number(maximum||0))e.push("المبلغ المعتمد لا يمكن أن يتجاوز أقصى مبلغ مسموح.");if(Number(form.financing_ratio)>100)e.push("نسبة التمويل تتجاوز الحد المسموح.");setErrors(e);return!e.length};
 const save=async(status)=>{if(!validate())return;setBusy(true);setMessage("");try{const customer=await pledgesService.createPledgeCustomer(companyId,{customer_name:form.customer_name,identity_type:form.identity_type,identity_number:form.identity_number,phone:form.phone,address:form.address,risk_level:form.risk_level,notes:form.notes});const pledge=await pledgesService.createPledge(companyId,{pledge_no:form.pledge_no,customer_id:customer.customer_id,customer_name:form.customer_name,branch:form.branch,created_by:user.username||user.name||"",pledge_date:form.pledge_date,due_date:form.due_date,status,requested_amount:Number(form.requested_amount||0),approved_amount:Number(form.approved_amount||0),total_fees:Number(form.total_fees||0),notes:form.notes});const details=[form.asset_model&&`الموديل: ${form.asset_model}`,form.accessories&&`الملحقات: ${form.accessories}`,form.plate_no&&`اللوحة: ${form.plate_no}`,form.chassis_no&&`الشاصي: ${form.chassis_no}`,form.manufacture_year&&`سنة الصنع: ${form.manufacture_year}`,form.document_type&&`نوع الوثيقة: ${form.document_type}`,form.document_number&&`رقم الوثيقة: ${form.document_number}`,form.property_location&&`موقع العقار: ${form.property_location}`,form.owner_name&&`المالك: ${form.owner_name}`].filter(Boolean).join("، ");await pledgesService.createPledgeAsset(companyId,{pledge_id:pledge.pledge_id,asset_type:form.asset_type,asset_name:form.asset_name||form.document_type,asset_description:form.asset_description||details,serial_number:form.serial_number||form.chassis_no||form.document_number,gold_weight:precious?Number(form.gold_weight||0):null,gold_karat:precious?form.gold_karat:null,condition_status:form.condition_status,ownership_proof:form.ownership_proof,estimated_market_value:market,accepted_pledge_value:accepted,financing_ratio:Number(form.financing_ratio||0),max_allowed_amount:maximum,vault_no:form.vault_no,shelf_no:form.shelf_no,bag_no:form.bag_no,notes:details});setMessage(status==="مسودة"?"تم حفظ الرهن كمسودة.":"تم إرسال الرهن للاعتماد.");setForm(defaultForm);setStep(1)}catch(e){console.error("Create pledge error",e);setMessage("تعذر حفظ الرهن، يرجى مراجعة البيانات والإعدادات.")}finally{setBusy(false)}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="إنشاء رهن جديد" desc={`الخطوة ${step} من 4`}/>{message&&<div className="rounded-2xl bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}<ErrorBox text={errors.join(" ")}/><div className="flex flex-wrap gap-2">{["بيانات العميل","بيانات الأصل","بيانات الرهن","مراجعة واعتماد"].map((x,i)=><span key={x} className={"rounded-xl px-3 py-2 text-xs font-bold "+(step===i+1?"bg-violet-700 text-white":"bg-slate-100")}>{i+1}. {x}</span>)}</div>
 {step===1&&<div className="panel grid gap-4 p-5 md:grid-cols-3"><PledgeField form={form} onChange={set} name="customer_name" label="الاسم" required/><PledgeField form={form} onChange={set} name="identity_number" label="رقم الهوية" required/><PledgeField form={form} onChange={set} name="identity_type" label="نوع الهوية"/><PledgeField form={form} onChange={set} name="phone" label="الجوال" required/><PledgeField form={form} onChange={set} name="address" label="العنوان"/><label className="text-sm font-bold">مستوى المخاطر<select className="field mt-1" value={form.risk_level??""} onChange={e=>set("risk_level",e.target.value)}>{["عادي","متوسط","مرتفع"].map(x=><option key={x}>{x}</option>)}</select></label><PledgeField form={form} onChange={set} name="notes" label="ملاحظات"/></div>}
 {step===2&&<div className="panel grid gap-4 p-5 md:grid-cols-4"><label className="text-sm font-bold">نوع الأصل *<select className="field mt-1" value={form.asset_type??""} onChange={e=>set("asset_type",e.target.value)}>{pledgeAssetTypes.map(x=><option key={x}>{x}</option>)}</select></label><AssetFields form={{...form,estimated_market_value:market}} set={set}/><PledgeField form={form} onChange={set} name="vault_no" label="رقم الخزنة"/><PledgeField form={form} onChange={set} name="shelf_no" label="رقم الرف"/><PledgeField form={form} onChange={set} name="bag_no" label="رقم الكيس"/></div>}
 {step===3&&<div className="panel grid gap-4 p-5 md:grid-cols-3"><PledgeField form={form} onChange={set} name="pledge_no" label="رقم الرهن"/><PledgeField form={form} onChange={set} name="branch" label="الفرع"/><PledgeField form={form} onChange={set} name="pledge_date" label="تاريخ الرهن" type="date" required/><PledgeField form={form} onChange={set} name="due_date" label="تاريخ الاستحقاق" type="date" required/><PledgeField form={form} onChange={set} name="requested_amount" label="المبلغ المطلوب" type="number"/><PledgeField form={form} onChange={set} name="approved_amount" label="المبلغ المعتمد" type="number"/><PledgeField form={form} onChange={set} name="total_fees" label="الرسوم" type="number"/><PledgeField form={form} onChange={set} name="notes" label="الملاحظات"/></div>}
 {step===4&&<div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><h3 className="font-black">ملخص العميل</h3><p>{form.customer_name}</p><p>{form.identity_number} • {form.phone}</p><Risk value={form.risk_level}/></div><div className="panel p-5"><h3 className="font-black">ملخص الأصل</h3><p>{form.asset_type} • {form.asset_description||form.asset_name||form.document_type}</p><p>القيمة المقبولة: <Money value={accepted}/></p></div><div className="panel p-5"><h3 className="font-black">ملخص التمويل</h3><p>المعتمد: <Money value={form.approved_amount}/></p><p>الحد الأقصى: <Money value={maximum}/></p><p>الاستحقاق: {form.due_date}</p></div></div>}
 <div className="flex gap-2">{step>1&&<button className="btn-secondary" onClick={()=>setStep(x=>x-1)}>السابق</button>}{step<4?<button className="btn-primary" onClick={()=>setStep(x=>x+1)}>التالي</button>:<><button disabled={busy} className="btn-secondary" onClick={()=>save("مسودة")}>حفظ كمسودة</button><button disabled={busy} className="btn-primary" onClick={()=>save("بانتظار الاعتماد")}>إرسال للاعتماد</button></>}</div></div>;
}

const contractLabels={customer_name:"صاحب الرهن",branch:"الفرع",pledge_date:"تاريخ الرهن",due_date:"تاريخ الاستحقاق",requested_amount:"المبلغ المطلوب",approved_amount:"المبلغ المعتمد",total_fees:"الرسوم",total_paid:"المدفوع",remaining_amount:"المتبقي",status:"الحالة",approval_status:"حالة الاعتماد",notes:"ملاحظات"};
export function PledgeContractsPage(props={}){
 const companyId=companyIdOf(props),[filters,setFilters]=useState({status:"all",branch:"",customer_name:""}),data=useLoad(()=>pledgesService.listPledges(companyId,Object.fromEntries(Object.entries(filters).filter(([,v])=>v&&v!=="all"))),[companyId,filters.status,filters.branch,filters.customer_name]),[selected,setSelected]=useState(null),[detailLoading,setDetailLoading]=useState(false);
 const open=async(row)=>{setDetailLoading(true);try{const[assets,customers]=await Promise.all([pledgesService.listPledgeAssets(companyId,row.pledge_id),pledgesService.listPledgeCustomers(companyId)]);const customer=customers.find(x=>x.customer_id===row.customer_id)||{};setSelected({...row,...customer,asset:assets[0]||{},assets})}catch(e){console.error("Pledge contract details error",e);setSelected({...row,asset:{},assets:[]})}finally{setDetailLoading(false)}};
 const change=async(row,status)=>{try{await pledgesService.changePledgeStatus(companyId,row.pledge_id,status,"تغيير من شاشة العقود",props.currentUser?.username||"");await data.load()}catch(e){console.error("Pledge status error",e)}};
 const print=(type)=>{if(!selected)return;import("./PledgePrintTemplates").then(({printPledgeDocument})=>printPledgeDocument(type,selected,props.currentCompany||{})).catch(e=>console.error("Pledge print load error",e))};
 return <div className="space-y-5" dir="rtl"><PageTitle title="عقود الرهن"/><ErrorBox text={data.error}/><div className="panel grid gap-3 p-4 md:grid-cols-3"><select className="field" value={filters.status} onChange={e=>setFilters(prev=>({...prev,status:e.target.value}))}><option value="all">كل الحالات</option>{pledgeStatuses.map(x=><option key={x}>{x}</option>)}</select><input className="field" placeholder="الفرع" value={filters.branch??""} onChange={e=>setFilters(prev=>({...prev,branch:e.target.value}))}/><input className="field" placeholder="صاحب الرهن" value={filters.customer_name??""} onChange={e=>setFilters(prev=>({...prev,customer_name:e.target.value}))}/></div>{data.loading?<Loading/>:data.rows.length?<div className="panel overflow-x-auto p-4"><table><thead><tr>{["رقم الرهن","صاحب الرهن","الفرع","المبلغ المعتمد","تاريخ الرهن","تاريخ الاستحقاق","الحالة","حالة الاعتماد","إجراءات"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.branch}</td><td><Money value={x.approved_amount}/></td><td>{x.pledge_date}</td><td>{x.due_date}</td><td>{x.status}</td><td>{x.approval_status}</td><td className="whitespace-nowrap"><button className="btn-secondary !h-8" onClick={()=>open(x)}>عرض</button> <select className="field !h-8 !w-36" value={x.status??""} onChange={e=>change(x,e.target.value)}>{pledgeStatuses.map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>:<Empty/>}{detailLoading&&<Loading/>}{selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div className="panel mx-auto w-full max-w-4xl p-6"><PageTitle title={`عقد رهن عيني — ${selected.pledge_no}`}><button onClick={()=>setSelected(null)}>إغلاق</button></PageTitle><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(contractLabels).map(([key,label])=><div className="rounded-xl bg-slate-50 p-3" key={key}><b>{label}</b><p>{String(selected[key]??"غير محدد")}</p></div>)}</div><div className="mt-4 rounded-xl border p-4"><h3 className="font-black">الأصل المرهون</h3><p>{selected.asset?.asset_type||"غير محدد"} — {selected.asset?.asset_description||selected.asset?.asset_name||"غير محدد"}</p></div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>print("contract")}>طباعة عقد رهن عيني</button><button className="btn-secondary" onClick={()=>print("receipt")}>طباعة سند استلام أصل مرهون</button><button className="btn-secondary" onClick={()=>print("redemption")}>طباعة إشعار فك رهن</button></div></div></div>}</div>;
}

export function PledgeValuationsPage(props={}){
 const companyId=companyIdOf(props),pledges=useLoad(()=>pledgesService.listPledges(companyId),[companyId]),[form,setForm]=useState({pledge_id:"",customer_name:"",branch:"",asset_id:"",valuation_date:today(),gold_weight:0,gold_karat:"24",gram_price:0,market_value:0,quick_sale_value:0,safety_discount_percent:10,financing_ratio:70,risk_notes:""}),[assets,setAssets]=useState([]),[message,setMessage]=useState(""),[loadingAssets,setLoadingAssets]=useState(false);
 const selectedAsset=assets.find(x=>x.asset_id===form.asset_id)||{},precious=preciousTypes.includes(selectedAsset.asset_type);
 const selectPledge=async(value)=>{const pledge=pledges.rows.find(x=>x.pledge_id===value)||{};setForm(prev=>({...prev,pledge_id:value,asset_id:"",customer_name:pledge.customer_name||"",branch:pledge.branch||""}));setLoadingAssets(true);try{const rows=value?await pledgesService.listPledgeAssets(companyId,value):[];setAssets(Array.isArray(rows)?rows:[])}catch(e){console.error("Pledge assets load error",e);setAssets([])}finally{setLoadingAssets(false)}};
 const market=precious?Number(form.gold_weight||0)*Number(form.gram_price||0):Number(form.market_value||0),accepted=precious?market*(1-Number(form.safety_discount_percent||0)/100):Number(form.quick_sale_value||market),max=accepted*Number(form.financing_ratio||0)/100;
 const save=async()=>{try{if(!form.pledge_id||!form.asset_id)throw new Error("اختر الرهن والأصل المرهون.");await pledgesService.createAssetValuation(companyId,{...form,market_value:market,accepted_value:accepted,max_allowed_amount:max});setMessage("تم حفظ التقييم بنجاح.")}catch(e){console.error("Valuation save error",e);setMessage(e.message||"تعذر حفظ التقييم.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="تقييم الأصول"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel grid gap-4 p-5 md:grid-cols-3"><label className="text-sm font-bold">اختر الرهن<select className="field mt-1" value={form.pledge_id??""} onChange={e=>selectPledge(e.target.value)}><option value="">اختر الرهن</option>{pledges.rows.map(x=><option key={x.pledge_id} value={x.pledge_id}>{x.pledge_no} - {x.customer_name}</option>)}</select></label><label className="text-sm font-bold">صاحب الرهن<input className="field mt-1 bg-slate-50" readOnly value={form.customer_name??""}/></label><label className="text-sm font-bold">الأصل المرهون<select className="field mt-1" disabled={!form.pledge_id||loadingAssets} value={form.asset_id??""} onChange={e=>{const asset=assets.find(x=>x.asset_id===e.target.value)||{};setForm(prev=>({...prev,asset_id:e.target.value,gold_weight:asset.gold_weight||0,gold_karat:asset.gold_karat||"24",market_value:asset.estimated_market_value||0,quick_sale_value:asset.accepted_pledge_value||0,financing_ratio:asset.financing_ratio||70}))}}><option value="">{loadingAssets?"جاري تحميل الأصول...":"اختر الأصل المرهون"}</option>{assets.map(x=><option key={x.asset_id} value={x.asset_id}>{x.asset_type} - {x.asset_description||x.asset_name}</option>)}</select></label>{precious&&<><ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="gold_weight" label="الوزن"/><ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="gram_price" label="سعر الجرام"/><ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="safety_discount_percent" label="نسبة خصم الأمان"/></>} {!precious&&<><ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="market_value" label="القيمة السوقية"/><ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="quick_sale_value" label="قيمة البيع السريع"/></>}<ValuationNumberField form={form} onChange={(name,value)=>setForm(prev=>({...prev,[name]:value}))} name="financing_ratio" label="نسبة التمويل"/></div><div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><small>القيمة السوقية</small><b className="block text-xl"><Money value={market}/></b></div><div className="panel p-5"><small>القيمة المقبولة</small><b className="block text-xl"><Money value={accepted}/></b></div><div className="panel p-5"><small>أقصى مبلغ مسموح</small><b className="block text-xl"><Money value={max}/></b></div></div><button className="btn-primary" onClick={save}>حفظ التقييم</button></div>;
}
