import React,{useEffect,useMemo,useState} from "react";
import { pledgesService,pledgeAssetTypes,pledgeNotificationTypes,pledgePaymentTypes } from "../../services/pledges";
import { companyIdOf,Empty,ErrorBox,Loading,Money,PageTitle } from "./PledgesCorePages";

const handled="تعذر تحميل البيانات، يرجى مراجعة الإعدادات أو الاتصال.";
const useRows=(loader,deps=[])=>{const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{const x=await loader();setRows(Array.isArray(x)?x:[]);setError("")}catch(e){console.error("Pledges page error",e);setRows([]);setError(handled)}finally{setLoading(false)}};useEffect(()=>{load()},deps);return{rows,loading,error,load}};
const Table=({headers=[],rows=[],render})=>rows.length?<div className="panel overflow-x-auto p-4"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table></div>:<Empty/>;
const OperationalNote=()=> <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4 text-sm font-bold text-violet-800">هذه الوحدة تشغيلية لإدارة الرهون العينية ولا تقوم بإنشاء قيود محاسبية تلقائية.</div>;
const printTemplate=(title,content)=>{try{const w=window.open("","_blank");if(!w)throw new Error("تعذر فتح نافذة الطباعة");w.document.write(`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Tahoma,Arial,sans-serif;padding:35px;line-height:2;color:#172033}h1{color:#312e81;border-bottom:2px solid #312e81;padding-bottom:12px}.box{border:1px solid #cbd5e1;border-radius:10px;padding:14px;margin:12px 0}.sign{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:50px}</style></head><body><h1>${title}</h1>${content}<div class="sign"><div>توقيع العميل:</div><div>توقيع الموظف:</div><div>اعتماد الإدارة:</div></div></body></html>`);w.document.close();w.focus();w.print()}catch(e){console.error("Pledge print error",e)}};

export function PledgeVaultPage(props={}){
 const companyId=companyIdOf(props),assets=useRows(()=>pledgesService.getVaultAssetsReport(companyId),[companyId]),pledges=useRows(()=>pledgesService.listPledges(companyId),[companyId]),locations=useRows(()=>pledgesService.listStorageLocations(companyId),[companyId]),[form,setForm]=useState({branch:"",vault_no:"",shelf_no:"",bag_no:"",location_description:""}),[selectedLocation,setSelectedLocation]=useState(""),[message,setMessage]=useState("");
 const ownerByPledge=useMemo(()=>new Map((pledges.rows||[]).map(row=>[row.pledge_id,row])),[pledges.rows]);
 const add=async()=>{try{const saved=await pledgesService.createStorageLocation(companyId,form);setSelectedLocation(saved?.location_id||"");setMessage("تمت إضافة موقع الحفظ.");await locations.load()}catch(e){console.error("Storage location error",e);setMessage("تعذر حفظ موقع التخزين.")}};
 const move=async(row)=>{const location=(locations.rows||[]).find(x=>x.location_id===selectedLocation);if(!location)return setMessage("اختر موقع التخزين المحدد أولًا.");try{await pledgesService.updatePledgeAsset(companyId,row.asset_id,{storage_location_id:location.location_id,vault_no:location.vault_no||"",shelf_no:location.shelf_no||"",bag_no:location.bag_no||"",asset_status:"داخل الخزنة"});setMessage("تم نقل الأصل إلى الموقع المحدد وتسجيل الحركة.");await assets.load()}catch(e){console.error("Vault movement error",e);setMessage("تعذر نقل الأصل.")}};
 const display=value=>String(value||"").trim()||"غير محدد";
 return <div className="space-y-5" dir="rtl"><PageTitle title="خزنة الرهون"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<ErrorBox text={assets.error||pledges.error||locations.error}/><div className="panel grid gap-3 p-4 md:grid-cols-5"><input className="field" placeholder="الفرع" value={form.branch??""} onChange={e=>setForm(prev=>({...prev,branch:e.target.value}))}/><input className="field" placeholder="الخزنة" value={form.vault_no??""} onChange={e=>setForm(prev=>({...prev,vault_no:e.target.value}))}/><input className="field" placeholder="الرف" value={form.shelf_no??""} onChange={e=>setForm(prev=>({...prev,shelf_no:e.target.value}))}/><input className="field" placeholder="الكيس" value={form.bag_no??""} onChange={e=>setForm(prev=>({...prev,bag_no:e.target.value}))}/><input className="field" placeholder="وصف الموقع" value={form.location_description??""} onChange={e=>setForm(prev=>({...prev,location_description:e.target.value}))}/><button className="btn-primary" onClick={add}>إضافة موقع تخزين</button><select className="field md:col-span-2" value={selectedLocation} onChange={e=>setSelectedLocation(e.target.value)}><option value="">اختر الموقع المحدد للنقل</option>{(locations.rows||[]).map(x=><option key={x.location_id} value={x.location_id}>{display(x.branch)} / خزنة {display(x.vault_no)} / رف {display(x.shelf_no)} / كيس {display(x.bag_no)}</option>)}</select></div>{assets.loading||pledges.loading?<Loading/>:<Table headers={["رقم الرهن","صاحب الرهن","نوع الأصل","وصف الأصل","الخزنة","الرف","الكيس","حالة الأصل","إجراء"]} rows={assets.rows||[]} render={x=>{const pledge=ownerByPledge.get(x.pledge_id)||{};return <tr key={x.asset_id}><td>{pledge.pledge_no||x.pledge_id}</td><td>{pledge.customer_name||"غير محدد"}</td><td>{x.asset_type||"غير محدد"}</td><td>{x.asset_description||x.asset_name||"غير محدد"}</td><td>{display(x.vault_no)}</td><td>{display(x.shelf_no)}</td><td>{display(x.bag_no)}</td><td>{display(x.asset_status)}</td><td><button className="btn-secondary !h-8" onClick={()=>move(x)}>نقل إلى الموقع المحدد</button></td></tr>}}/>}</div>;
}

export function PledgeRedemptionPage(props={}){
 const companyId=companyIdOf(props),[search,setSearch]=useState(""),[pledge,setPledge]=useState(null),[balance,setBalance]=useState(null),[amount,setAmount]=useState(0),[message,setMessage]=useState("");
 const find=async()=>{try{const rows=await pledgesService.listPledges(companyId);const x=rows.find(r=>r.pledge_no===search||r.pledge_id===search)||null;setPledge(x);setBalance(x?await pledgesService.calculatePledgeBalance(companyId,x.pledge_id):null);if(!x)setMessage("لم يتم العثور على الرهن.")}catch(e){console.error("Redemption search error",e);setMessage(handled)}};
 const pay=async(full=false)=>{if(!pledge)return;try{const value=full?Number(balance?.remaining_amount||0):Number(amount||0);await pledgesService.createPledgePayment(companyId,{pledge_id:pledge.pledge_id,payment_date:new Date().toISOString().slice(0,10),payment_type:full?"سداد كامل":"سداد جزئي",amount:value,received_by:props.currentUser?.username||""});const next=await pledgesService.calculatePledgeBalance(companyId,pledge.pledge_id);setBalance(next);if(next?.remaining_amount<=0){await pledgesService.changePledgeStatus(companyId,pledge.pledge_id,"مفكوك","سداد كامل وفك الرهن");setMessage("تم السداد الكامل وتغيير الحالة إلى مفكوك.")}else setMessage("تم تسجيل الدفعة.")}catch(e){console.error("Pledge payment error",e);setMessage("تعذر تسجيل السداد.")}};
 const release=()=>pledge&&printTemplate("إشعار فك رهن",`<div class="box">رقم الرهن: ${pledge.pledge_no}<br>العميل: ${pledge.customer_name}<br>تم سداد كامل المبلغ وتسليم الأصل للعميل.</div><p>توقيع العميل: __________________</p>`);
 return <div className="space-y-5" dir="rtl"><PageTitle title="السداد وفك الرهن"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel flex gap-3 p-4"><input className="field" placeholder="رقم الرهن" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn-primary" onClick={find}>بحث</button></div>{pledge&&<><div className="grid gap-4 md:grid-cols-4">{[["المبلغ المعتمد",balance?.approved_amount],["الرسوم",balance?.total_fees],["المدفوع",balance?.total_paid],["المتبقي",balance?.remaining_amount]].map(([a,b])=><div className="panel p-5" key={a}><small>{a}</small><b className="block text-xl"><Money value={b}/></b></div>)}</div><div className="panel flex flex-wrap gap-3 p-4"><input type="number" className="field max-w-56" value={amount} onChange={e=>setAmount(e.target.valueAsNumber)}/><button className="btn-secondary" onClick={()=>pay(false)}>إضافة دفعة</button><button className="btn-primary" onClick={()=>pay(true)}>سداد كامل وفك الرهن</button><button className="btn-secondary" onClick={release}>طباعة إشعار فك رهن</button></div></>}</div>;
}

export function PledgeRenewalsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.listPledges(companyId),[companyId]),[message,setMessage]=useState("");
 const renew=async(row)=>{try{const settings=await pledgesService.listPledgeSettings(companyId),setting=settings.find(x=>x.asset_type===row.asset_type)||settings[0]||{};if(Number(row.renewal_count||0)>=Number(setting.max_renewal_count??2))throw new Error("تم بلوغ الحد الأقصى لعدد التمديدات.");const due=new Date(row.due_date);due.setDate(due.getDate()+Number(setting.default_pledge_days||30));await pledgesService.updatePledge(companyId,row.pledge_id,{due_date:due.toISOString().slice(0,10),renewal_count:Number(row.renewal_count||0)+1,status:"ممدد"});await pledgesService.changePledgeStatus(companyId,row.pledge_id,"ممدد","تمديد مدة الرهن");setMessage("تم تمديد الرهن.");data.load()}catch(e){console.error("Pledge renewal error",e);setMessage(e.message||"تعذر التمديد.")}};
 const rows=data.rows.filter(x=>["نشط","مستحق قريبًا","ممدد"].includes(x.status));
 return <div className="space-y-5" dir="rtl"><PageTitle title="التمديد والتجديد"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}{data.loading?<Loading/>:<Table headers={["رقم الرهن","العميل","الاستحقاق","عدد التمديدات","الحالة","إجراء"]} rows={rows} render={x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.due_date}</td><td>{x.renewal_count||0}</td><td>{x.status}</td><td><button className="btn-primary !h-8" onClick={()=>renew(x)}>تمديد 30 يومًا</button></td></tr>}/>}</div>;
}

export function PledgeDefaultsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.getOverduePledgesReport(companyId),[companyId]),[message,setMessage]=useState("");
 const liquidate=async(row)=>{try{await pledgesService.changePledgeStatus(companyId,row.pledge_id,"تحت التصفية","تجاوز تاريخ الاستحقاق");await pledgesService.createDisposal(companyId,{pledge_id:row.pledge_id,disposal_date:new Date().toISOString().slice(0,10),disposal_status:"مسودة",reason:"تعثر الرهن"});setMessage("تم تحويل الرهن إلى التصفية وإنشاء سجل تصرف.");data.load()}catch(e){console.error("Liquidation error",e);setMessage(e.message||"تعذر بدء التصفية.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="التعثر والتصفية"/>{message&&<div className="rounded-xl bg-amber-50 p-3 font-bold text-amber-800">{message}</div>}{data.loading?<Loading/>:<Table headers={["الرهن","العميل","الاستحقاق","أيام التأخير","المتبقي","الحالة","إجراء"]} rows={data.rows} render={x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.due_date}</td><td>{Math.max(0,Math.floor((Date.now()-new Date(x.due_date).getTime())/86400000))}</td><td><Money value={x.remaining_amount}/></td><td>{x.status}</td><td><button className="btn-secondary !h-8" onClick={()=>printTemplate("إشعار تأخير",`<div class="box">العميل: ${x.customer_name}<br>الرهن: ${x.pledge_no}<br>يرجى السداد قبل اتخاذ إجراءات التصفية.</div>`)}>إشعار نهائي</button> <button className="btn-primary !h-8" onClick={()=>liquidate(x)}>تحت التصفية</button></td></tr>}/>}</div>;
}

export function PledgeNotificationsPage(props={}){
 const companyId=companyIdOf(props),due=useRows(()=>pledgesService.getDuePledgesReport(companyId),[companyId]),notifications=useRows(()=>pledgesService.listPledgeNotifications(companyId),[companyId]),[message,setMessage]=useState("");
 const generate=async(row)=>{try{await pledgesService.createPledgeNotification(companyId,{pledge_id:row.pledge_id,customer_id:row.customer_id,notification_type:"تذكير قبل الاستحقاق",notification_date:new Date().toISOString().slice(0,10),message:`تذكير بقرب استحقاق الرهن رقم ${row.pledge_no}`});setMessage("تم إنشاء الإشعار الداخلي.");notifications.load()}catch(e){console.error("Notification error",e);setMessage("تعذر إنشاء الإشعار.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="إشعارات الاستحقاق"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel p-5"><h3 className="mb-3 font-black">رهون مستحقة قريبًا</h3>{due.rows.length?due.rows.map(x=><div className="flex items-center gap-3 border-b py-2" key={x.pledge_id}><span>{x.pledge_no} — {x.customer_name} — {x.due_date}</span><button className="btn-secondary mr-auto !h-8" onClick={()=>generate(x)}>إنشاء تذكير</button></div>):<Empty/>}</div><Table headers={["النوع","التاريخ","الرسالة","الحالة","إجراء"]} rows={notifications.rows} render={x=><tr key={x.notification_id}><td>{x.notification_type}</td><td>{x.notification_date}</td><td>{x.message}</td><td>{x.status}</td><td><button className="btn-primary !h-8" onClick={()=>pledgesService.markNotificationSent(companyId,x.notification_id).then(notifications.load)}>تحديد كمرسل</button></td></tr>}/></div>;
}

export function PledgeReportsPage(props={}){
 const companyId=companyIdOf(props),[type,setType]=useState("active"),[filters,setFilters]=useState({customer:"",branch:"",asset_type:"all"}),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const reportTitles={active:"الرهون النشطة",due:"الرهون المستحقة",overdue:"الرهون المتأخرة",vault:"الأصول داخل الخزنة",customer:"الرهون حسب العميل",branch:"الرهون حسب الفرع",asset:"الرهون حسب نوع الأصل",redeemed:"الرهون المفكوكة",disposed:"الرهون المصفاة",risk:"تقرير مخاطر الرهون",movement:"سجل حركة الأصل"};
 const load=async()=>{setLoading(true);setError("");try{const[allPledges,allAssets,audits]=await Promise.all([pledgesService.listPledges(companyId),pledgesService.getVaultAssetsReport(companyId),type==="movement"?pledgesService.listPledgeAuditLogs(companyId):Promise.resolve([])]);const pledgesList=Array.isArray(allPledges)?allPledges:[],assetsList=Array.isArray(allAssets)?allAssets:[],assetByPledge=new Map();assetsList.forEach(asset=>{if(!assetByPledge.has(asset.pledge_id))assetByPledge.set(asset.pledge_id,asset)});let base=pledgesList;if(type==="active")base=base.filter(x=>["نشط","مستحق قريبًا","ممدد"].includes(x.status));if(type==="due"){const end=Date.now()+7*86400000;base=base.filter(x=>x.due_date&&new Date(x.due_date).getTime()>=Date.now()&&new Date(x.due_date).getTime()<=end)}if(type==="overdue"||type==="risk")base=base.filter(x=>x.status==="متأخر"||(x.due_date&&new Date(x.due_date).getTime()<Date.now()&&!["مفكوك","ملغي","مصفى"].includes(x.status)));if(type==="redeemed")base=base.filter(x=>x.status==="مفكوك");if(type==="disposed")base=base.filter(x=>x.status==="مصفى");if(type==="vault")base=assetsList.map(asset=>({...pledgesList.find(x=>x.pledge_id===asset.pledge_id),asset}));else if(type==="movement")base=(audits||[]).filter(x=>x.action_type==="vault_movement").map(log=>{const asset=assetsList.find(x=>x.asset_id===log.entity_id)||{},pledge=pledgesList.find(x=>x.pledge_id===asset.pledge_id)||{};return{...pledge,asset,movement_date:log.action_at,movement_reason:log.reason}});else base=base.map(pledge=>({...pledge,asset:assetByPledge.get(pledge.pledge_id)||{}}));base=base.filter(x=>(!filters.customer||String(x.customer_name||"").includes(filters.customer))&&(!filters.branch||String(x.branch||"").includes(filters.branch))&&(filters.asset_type==="all"||x.asset?.asset_type===filters.asset_type));setRows(base)}catch(e){console.error("Pledge report error",e);setError(handled);setRows([])}finally{setLoading(false)}};
 useEffect(()=>{load()},[companyId,type,filters.customer,filters.branch,filters.asset_type]);
 const print=()=>{const body=rows.map(x=>`<tr><td>${x.pledge_no||x.pledge_id||"—"}</td><td>${x.customer_name||"—"}</td><td>${x.branch||"—"}</td><td>${x.asset?.asset_type||"—"}</td><td>${x.asset?.asset_description||x.asset?.asset_name||"—"}</td><td>${Number(x.approved_amount||0).toFixed(2)}</td><td>${Number(x.remaining_amount||0).toFixed(2)}</td><td>${x.pledge_date||"—"}</td><td>${x.due_date||"—"}</td><td>${x.status||x.asset?.asset_status||"—"}</td><td>${x.approval_status||"—"}</td></tr>`).join("");printTemplate(reportTitles[type],`<div class="box">تاريخ التقرير: ${new Date().toLocaleDateString("ar-SA")}<br>الفلاتر: العميل ${filters.customer||"الكل"}، الفرع ${filters.branch||"الكل"}، نوع الأصل ${filters.asset_type==="all"?"الكل":filters.asset_type}<br>إجمالي السجلات: ${rows.length}</div><table style="width:100%;border-collapse:collapse;font-size:11px"><thead><tr><th>رقم الرهن</th><th>صاحب الرهن</th><th>الفرع</th><th>نوع الأصل</th><th>الوصف</th><th>المعتمد</th><th>المتبقي</th><th>تاريخ الرهن</th><th>الاستحقاق</th><th>الحالة</th><th>الاعتماد</th></tr></thead><tbody>${body}</tbody></table><div style="margin-top:40px;display:flex;justify-content:space-around"><span>توقيع الموظف: __________</span><span>اعتماد الإدارة: __________</span></div>`)};
 return <div className="space-y-5" dir="rtl"><PageTitle title="تقارير الرهون"><button className="btn-primary" disabled={!rows.length} onClick={print}>طباعة التقرير</button></PageTitle><OperationalNote/><ErrorBox text={error}/><div className="panel grid gap-3 p-4 md:grid-cols-4"><select className="field" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(reportTitles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input className="field" placeholder="صاحب الرهن" value={filters.customer??""} onChange={e=>setFilters(prev=>({...prev,customer:e.target.value}))}/><input className="field" placeholder="الفرع" value={filters.branch??""} onChange={e=>setFilters(prev=>({...prev,branch:e.target.value}))}/><select className="field" value={filters.asset_type} onChange={e=>setFilters(prev=>({...prev,asset_type:e.target.value}))}><option value="all">كل أنواع الأصول</option>{pledgeAssetTypes.map(x=><option key={x}>{x}</option>)}</select></div>{loading?<Loading/>:rows.length?<Table headers={["رقم الرهن","صاحب الرهن","الفرع","نوع الأصل","وصف الأصل","المبلغ المعتمد","المتبقي","تاريخ الرهن","تاريخ الاستحقاق","الحالة","حالة الاعتماد"]} rows={rows} render={(x,index)=><tr key={(x.pledge_id||x.asset?.asset_id||"row")+"-"+index}><td>{x.pledge_no||x.pledge_id||"غير محدد"}</td><td>{x.customer_name||"غير محدد"}</td><td>{x.branch||"غير محدد"}</td><td>{x.asset?.asset_type||"غير محدد"}</td><td>{x.asset?.asset_description||x.asset?.asset_name||"غير محدد"}</td><td><Money value={x.approved_amount}/></td><td><Money value={x.remaining_amount}/></td><td>{x.pledge_date||"غير محدد"}</td><td>{x.due_date||"غير محدد"}</td><td>{x.status||x.asset?.asset_status||"غير محدد"}</td><td>{x.approval_status||"غير محدد"}</td></tr>}/>:<div className="rounded-2xl border border-dashed p-8 text-center text-slate-500">لا توجد بيانات مطابقة للفلاتر.</div>}</div>;
}

export function PledgeSettingsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.listPledgeSettings(companyId),[companyId]),[form,setForm]=useState({asset_type:"ذهب",max_financing_ratio:70,default_pledge_days:30,max_renewal_count:2,reminder_days_before_due:3,default_storage_fee:0,default_valuation_fee:0,default_admin_fee:0,liquidation_after_delay_days:15,require_manager_approval:true,is_active:true}),[message,setMessage]=useState("");
 const save=async()=>{try{await pledgesService.upsertPledgeSetting(companyId,form);setMessage("تم حفظ إعدادات نوع الأصل.");data.load()}catch(e){console.error("Pledge settings error",e);setMessage("تعذر حفظ الإعدادات.")}};
 const F=({k,l})=><label className="text-sm font-bold">{l}<input type="number" className="field mt-1" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.valueAsNumber})}/></label>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="إعدادات الرهون"/><OperationalNote/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel grid gap-4 p-5 md:grid-cols-3"><label className="text-sm font-bold">نوع الأصل<select className="field mt-1" value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value})}>{pledgeAssetTypes.map(x=><option key={x}>{x}</option>)}</select></label><F k="max_financing_ratio" l="نسبة التمويل القصوى"/><F k="default_pledge_days" l="مدة الرهن الافتراضية"/><F k="max_renewal_count" l="أقصى عدد تمديدات"/><F k="reminder_days_before_due" l="أيام التذكير"/><F k="default_storage_fee" l="رسوم الحفظ"/><F k="default_valuation_fee" l="رسوم التقييم"/><F k="default_admin_fee" l="الرسوم الإدارية"/><F k="liquidation_after_delay_days" l="التصفية بعد أيام"/><label><input type="checkbox" checked={form.require_manager_approval} onChange={e=>setForm({...form,require_manager_approval:e.target.checked})}/> يتطلب اعتماد المدير</label><label><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> مفعل</label><button className="btn-primary" onClick={save}>حفظ</button></div><Table headers={["نوع الأصل","نسبة التمويل","المدة","التمديدات","التذكير","الحالة"]} rows={data.rows} render={x=><tr key={x.setting_id}><td>{x.asset_type}</td><td>{x.max_financing_ratio}%</td><td>{x.default_pledge_days} يوم</td><td>{x.max_renewal_count}</td><td>{x.reminder_days_before_due} أيام</td><td>{x.is_active?"مفعل":"غير مفعل"}</td></tr>}/></div>;
}
