import React,{useEffect,useMemo,useState} from "react";
import { pledgesService,pledgeAssetTypes,pledgeStatuses } from "../../services/pledges";

export const companyIdOf=(props={})=>props.currentCompany?.company_id||props.currentCompany?.id||props.currentUser?.company_id||"";
export const ErrorBox=({text})=>text?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{text}</div>:null;
export const Empty=()=> <div className="rounded-2xl border border-dashed p-8 text-center text-slate-400">لا توجد بيانات محفوظة بعد</div>;
export const Loading=()=> <div className="panel p-8 text-center font-bold text-slate-500">جاري تحميل البيانات...</div>;
export const PageTitle=({title,desc,children})=><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">{title}</h1>{desc&&<p className="mt-1 text-sm text-slate-500">{desc}</p>}</div>{children}</div>;
export const Money=({value})=><>{new Intl.NumberFormat("ar-SA",{maximumFractionDigits:2}).format(Number(value||0))} ر.س</>;
export const Risk=({value="عادي"})=><span className={"rounded-full px-3 py-1 text-xs font-bold "+(value==="مرتفع"?"bg-red-100 text-red-700":value==="متوسط"?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700")}>{value}</span>;
const handled="تعذر تحميل البيانات، يرجى مراجعة الإعدادات أو الاتصال.";

const useLoad=(loader,deps=[])=>{
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const result=await loader();setRows(Array.isArray(result)?result:[])}catch(e){console.error("Pledges page load error",e);setRows([]);setError(handled)}finally{setLoading(false)}};
 useEffect(()=>{load()},deps);return{rows,loading,error,load,setRows};
};

export function PledgesDashboardPage(props={}){
 const companyId=companyIdOf(props),[stats,setStats]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{setLoading(true);try{const x=await pledgesService.getPledgesDashboardStats(companyId);if(active)setStats(x||{})}catch(e){console.error("Pledges dashboard error",e);if(active)setError(handled)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[companyId]);
 if(loading)return <Loading/>;const cards=[["إجمالي الرهون النشطة",stats.active_count],["إجمالي المبالغ المصروفة",<Money value={stats.approved_amount_total}/>],["إجمالي قيمة الأصول المرهونة",<Money value={stats.asset_value_total}/>],["المستحقة خلال 7 أيام",stats.due_soon_count],["الرهون المتأخرة",stats.overdue_count],["الرهون المفكوكة",stats.redeemed_count],["الأصول تحت التصفية",stats.liquidation_count],["نسبة المخاطر",`${stats.risk_percent||0}%`]];
 const status=Object.entries((stats.pledges||[]).reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{}));
 const types=Object.entries((stats.assets||[]).reduce((a,x)=>(a[x.asset_type]=(a[x.asset_type]||0)+1,a),{}));
 const branches=Object.entries((stats.pledges||[]).reduce((a,x)=>(a[x.branch||"غير محدد"]=(a[x.branch||"غير محدد"]||0)+1,a),{}));
 const Chart=({title,data})=><div className="panel p-5"><h3 className="mb-4 font-black">{title}</h3>{data.length?data.map(([k,v])=><div className="mb-3" key={k}><div className="mb-1 flex justify-between text-xs font-bold"><span>{k}</span><span>{v}</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-violet-700" style={{width:`${Math.max(8,Math.min(100,v/Math.max(...data.map(x=>x[1]))*100))}%`}}/></div></div>):<Empty/>}</div>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="لوحة الرهون" desc="ملخص تشغيلي للأصول المرهونة والاستحقاقات"/><ErrorBox text={error}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([a,b])=><div className="panel p-5" key={a}><p className="text-sm font-bold text-slate-500">{a}</p><b className="mt-2 block text-2xl text-violet-800">{b??0}</b></div>)}</div><div className="grid gap-5 lg:grid-cols-3"><Chart title="رهون حسب الحالة" data={status}/><Chart title="رهون حسب نوع الأصل" data={types}/><Chart title="رهون حسب الفرع" data={branches}/></div></div>;
}

const today=()=>new Date().toISOString().slice(0,10);
const defaultForm={customer_name:"",identity_type:"هوية وطنية",identity_number:"",phone:"",address:"",risk_level:"عادي",asset_type:"ذهب",asset_name:"",asset_description:"",serial_number:"",gold_weight:"",gold_karat:"",condition_status:"جيد",ownership_proof:"",estimated_market_value:"",accepted_pledge_value:"",financing_ratio:70,max_allowed_amount:"",vault_no:"",shelf_no:"",bag_no:"",pledge_no:"",branch:"",pledge_date:today(),due_date:"",requested_amount:"",approved_amount:"",total_fees:"",notes:""};

export function NewPledgePage(props={}){
 const companyId=companyIdOf(props),user=props.currentUser||{},[step,setStep]=useState(1),[form,setForm]=useState(defaultForm),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[errors,setErrors]=useState([]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const validate=()=>{const e=[];if(!form.customer_name.trim())e.push("اسم العميل مطلوب.");if(!form.identity_number.trim())e.push("رقم الهوية مطلوب.");if(!form.phone.trim())e.push("رقم الجوال مطلوب.");if(!form.asset_type)e.push("نوع الأصل مطلوب.");if(!form.asset_description.trim())e.push("وصف الأصل مطلوب.");if(!form.pledge_date)e.push("تاريخ الرهن مطلوب.");if(!form.due_date)e.push("تاريخ الاستحقاق مطلوب.");if(form.pledge_date&&form.due_date&&form.due_date<=form.pledge_date)e.push("يجب أن يكون تاريخ الاستحقاق بعد تاريخ الرهن.");if(Number(form.approved_amount)>Number(form.max_allowed_amount||0))e.push("المبلغ المعتمد لا يمكن أن يتجاوز أقصى مبلغ مسموح.");if(Number(form.financing_ratio)>100)e.push("نسبة التمويل تتجاوز الحد المسموح.");setErrors(e);return!e.length};
 const save=async(status)=>{if(!validate())return;setBusy(true);setMessage("");try{const customer=await pledgesService.createPledgeCustomer(companyId,{customer_name:form.customer_name,identity_type:form.identity_type,identity_number:form.identity_number,phone:form.phone,address:form.address,risk_level:form.risk_level,notes:form.notes});const pledge=await pledgesService.createPledge(companyId,{pledge_no:form.pledge_no,customer_id:customer.customer_id,customer_name:form.customer_name,branch:form.branch,created_by:user.username||user.name||"",pledge_date:form.pledge_date,due_date:form.due_date,status,requested_amount:Number(form.requested_amount||0),approved_amount:Number(form.approved_amount||0),total_fees:Number(form.total_fees||0),approval_status:status==="بانتظار الاعتماد"?"غير معتمد":"غير معتمد",notes:form.notes});await pledgesService.createPledgeAsset(companyId,{pledge_id:pledge.pledge_id,asset_type:form.asset_type,asset_name:form.asset_name,asset_description:form.asset_description,serial_number:form.serial_number,gold_weight:Number(form.gold_weight||0),gold_karat:form.gold_karat,condition_status:form.condition_status,ownership_proof:form.ownership_proof,estimated_market_value:Number(form.estimated_market_value||0),accepted_pledge_value:Number(form.accepted_pledge_value||0),financing_ratio:Number(form.financing_ratio||0),max_allowed_amount:Number(form.max_allowed_amount||0),vault_no:form.vault_no,shelf_no:form.shelf_no,bag_no:form.bag_no});setMessage(status==="مسودة"?"تم حفظ الرهن كمسودة.":"تم إرسال الرهن للاعتماد.");setForm(defaultForm);setStep(1)}catch(e){console.error("Create pledge error",e);setMessage("تعذر حفظ الرهن، يرجى مراجعة البيانات والإعدادات.")}finally{setBusy(false)}};
 const Field=({k,label,type="text",required=false})=><label className="text-sm font-bold">{label}{required&&" *"}<input className="field mt-1" type={type} value={form[k]??""} onChange={e=>set(k,type==="number"?e.target.valueAsNumber:e.target.value)}/></label>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="إنشاء رهن جديد" desc={`الخطوة ${step} من 4`}/>{message&&<div className="rounded-2xl bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}<ErrorBox text={errors.join(" ")}/><div className="flex gap-2">{["بيانات العميل","بيانات الأصل","بيانات الرهن","مراجعة واعتماد"].map((x,i)=><span key={x} className={"rounded-xl px-3 py-2 text-xs font-bold "+(step===i+1?"bg-violet-700 text-white":"bg-slate-100")}>{i+1}. {x}</span>)}</div>
 {step===1&&<div className="panel grid gap-4 p-5 md:grid-cols-3"><Field k="customer_name" label="الاسم" required/><Field k="identity_number" label="رقم الهوية" required/><Field k="identity_type" label="نوع الهوية"/><Field k="phone" label="الجوال" required/><Field k="address" label="العنوان"/><label className="text-sm font-bold">مستوى المخاطر<select className="field mt-1" value={form.risk_level} onChange={e=>set("risk_level",e.target.value)}>{["عادي","متوسط","مرتفع"].map(x=><option key={x}>{x}</option>)}</select></label><Field k="notes" label="ملاحظات"/></div>}
 {step===2&&<div className="panel grid gap-4 p-5 md:grid-cols-4"><label className="text-sm font-bold">نوع الأصل *<select className="field mt-1" value={form.asset_type} onChange={e=>set("asset_type",e.target.value)}>{pledgeAssetTypes.map(x=><option key={x}>{x}</option>)}</select></label><Field k="asset_name" label="اسم الأصل"/><Field k="asset_description" label="الوصف" required/><Field k="serial_number" label="الرقم التسلسلي"/><Field k="gold_weight" label="الوزن للذهب" type="number"/><Field k="gold_karat" label="العيار للذهب"/><Field k="condition_status" label="الحالة"/><Field k="ownership_proof" label="إثبات الملكية"/><Field k="estimated_market_value" label="القيمة السوقية" type="number"/><Field k="accepted_pledge_value" label="القيمة المقبولة للرهن" type="number"/><Field k="financing_ratio" label="نسبة التمويل" type="number"/><Field k="max_allowed_amount" label="أقصى مبلغ مسموح" type="number"/><Field k="vault_no" label="رقم الخزنة"/><Field k="shelf_no" label="رقم الرف"/><Field k="bag_no" label="رقم الكيس"/></div>}
 {step===3&&<div className="panel grid gap-4 p-5 md:grid-cols-3"><Field k="pledge_no" label="رقم الرهن"/><Field k="branch" label="الفرع"/><Field k="pledge_date" label="تاريخ الرهن" type="date" required/><Field k="due_date" label="تاريخ الاستحقاق" type="date" required/><Field k="requested_amount" label="المبلغ المطلوب" type="number"/><Field k="approved_amount" label="المبلغ المعتمد" type="number"/><Field k="total_fees" label="الرسوم" type="number"/><Field k="notes" label="الملاحظات"/></div>}
 {step===4&&<div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><h3 className="font-black">ملخص العميل</h3><p>{form.customer_name}</p><p>{form.identity_number} • {form.phone}</p><Risk value={form.risk_level}/></div><div className="panel p-5"><h3 className="font-black">ملخص الأصل</h3><p>{form.asset_type} • {form.asset_description}</p><p>القيمة المقبولة: <Money value={form.accepted_pledge_value}/></p></div><div className="panel p-5"><h3 className="font-black">ملخص التمويل</h3><p>المعتمد: <Money value={form.approved_amount}/></p><p>الاستحقاق: {form.due_date}</p></div></div>}
 <div className="flex gap-2">{step>1&&<button className="btn-secondary" onClick={()=>setStep(x=>x-1)}>السابق</button>}{step<4?<button className="btn-primary" onClick={()=>setStep(x=>x+1)}>التالي</button>:<><button disabled={busy} className="btn-secondary" onClick={()=>save("مسودة")}>حفظ كمسودة</button><button disabled={busy} className="btn-primary" onClick={()=>save("بانتظار الاعتماد")}>إرسال للاعتماد</button></>}</div></div>;
}

export function PledgeContractsPage(props={}){
 const companyId=companyIdOf(props),[filters,setFilters]=useState({status:"all",branch:"",customer_name:""}),data=useLoad(()=>pledgesService.listPledges(companyId,Object.fromEntries(Object.entries(filters).filter(([,v])=>v&&v!=="all"))),[companyId,filters.status,filters.branch,filters.customer_name]),[selected,setSelected]=useState(null);
 const change=async(row,status)=>{try{await pledgesService.changePledgeStatus(companyId,row.pledge_id,status,"تغيير من شاشة العقود",props.currentUser?.username||"");await data.load()}catch(e){console.error("Pledge status error",e)}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="عقود الرهن"/><ErrorBox text={data.error}/><div className="panel grid gap-3 p-4 md:grid-cols-3"><select className="field" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="all">كل الحالات</option>{pledgeStatuses.map(x=><option key={x}>{x}</option>)}</select><input className="field" placeholder="الفرع" value={filters.branch} onChange={e=>setFilters({...filters,branch:e.target.value})}/><input className="field" placeholder="العميل" value={filters.customer_name} onChange={e=>setFilters({...filters,customer_name:e.target.value})}/></div>{data.loading?<Loading/>:data.rows.length?<div className="panel overflow-x-auto p-4"><table><thead><tr>{["رقم الرهن","العميل","الفرع","المبلغ المعتمد","تاريخ الرهن","تاريخ الاستحقاق","الحالة","الاعتماد","إجراءات"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.branch}</td><td><Money value={x.approved_amount}/></td><td>{x.pledge_date}</td><td>{x.due_date}</td><td>{x.status}</td><td>{x.approval_status}</td><td className="whitespace-nowrap"><button className="btn-secondary !h-8" onClick={()=>setSelected(x)}>عرض</button> <select className="field !h-8 !w-36" value={x.status} onChange={e=>change(x,e.target.value)}>{pledgeStatuses.map(s=><option key={s}>{s}</option>)}</select> <button className="text-red-700" onClick={()=>pledgesService.cancelPledge(companyId,x.pledge_id,"إلغاء من شاشة العقود").then(data.load)}>إلغاء</button></td></tr>)}</tbody></table></div>:<Empty/>}{selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="panel w-full max-w-2xl p-6"><PageTitle title={`عقد رهن عيني — ${selected.pledge_no}`}><button onClick={()=>setSelected(null)}>إغلاق</button></PageTitle><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(selected).filter(([k])=>["customer_name","branch","pledge_date","due_date","approved_amount","remaining_amount","status","notes"].includes(k)).map(([k,v])=><div className="rounded-xl bg-slate-50 p-3" key={k}><b>{k}</b><p>{String(v??"—")}</p></div>)}</div><button className="btn-primary mt-5" onClick={()=>window.print()}>طباعة عقد رهن عيني</button></div></div>}</div>;
}

export function PledgeValuationsPage(props={}){
 const companyId=companyIdOf(props),pledges=useLoad(()=>pledgesService.listPledges(companyId),[companyId]),[form,setForm]=useState({pledge_id:"",asset_id:"",valuation_date:today(),gold_weight:0,gold_karat:"24",gram_price:0,market_value:0,quick_sale_value:0,safety_discount_percent:10,financing_ratio:70,risk_notes:""}),[assets,setAssets]=useState([]),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{try{setAssets(form.pledge_id?await pledgesService.listPledgeAssets(companyId,form.pledge_id):[])}catch(e){console.error("Pledge assets load error",e);setAssets([])}})()},[companyId,form.pledge_id]);
 const market=form.gold_weight&&form.gram_price?Number(form.gold_weight)*Number(form.gram_price):Number(form.market_value||0),accepted=market*(1-Number(form.safety_discount_percent||0)/100),max=accepted*Number(form.financing_ratio||0)/100;
 const save=async()=>{try{await pledgesService.createAssetValuation(companyId,{...form,market_value:market,accepted_value:accepted,max_allowed_amount:max});setMessage("تم حفظ التقييم بنجاح.")}catch(e){console.error("Valuation save error",e);setMessage("تعذر حفظ التقييم.")}};
 const F=({k,l})=><label className="text-sm font-bold">{l}<input type="number" className="field mt-1" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.valueAsNumber})}/></label>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="تقييم الأصول"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel grid gap-4 p-5 md:grid-cols-3"><label>الرهن<select className="field mt-1" value={form.pledge_id} onChange={e=>setForm({...form,pledge_id:e.target.value,asset_id:""})}><option value="">اختر الرهن</option>{pledges.rows.map(x=><option key={x.pledge_id} value={x.pledge_id}>{x.pledge_no} — {x.customer_name}</option>)}</select></label><label>الأصل<select className="field mt-1" value={form.asset_id} onChange={e=>setForm({...form,asset_id:e.target.value})}><option value="">اختر الأصل</option>{assets.map(x=><option key={x.asset_id} value={x.asset_id}>{x.asset_type} — {x.asset_name||x.asset_description}</option>)}</select></label><F k="gold_weight" l="الوزن"/><F k="gram_price" l="سعر الجرام"/><F k="market_value" l="القيمة السوقية لغير الذهب"/><F k="quick_sale_value" l="قيمة البيع السريع"/><F k="safety_discount_percent" l="نسبة خصم الأمان"/><F k="financing_ratio" l="نسبة التمويل"/></div><div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><small>القيمة السوقية</small><b className="block text-xl"><Money value={market}/></b></div><div className="panel p-5"><small>القيمة المقبولة = السوقية - خصم الأمان</small><b className="block text-xl"><Money value={accepted}/></b></div><div className="panel p-5"><small>أقصى مبلغ = المقبولة × نسبة التمويل</small><b className="block text-xl"><Money value={max}/></b></div></div><button className="btn-primary" onClick={save}>حفظ التقييم</button></div>;
}
