import React,{useEffect,useMemo,useState} from "react";
import { pledgesService,pledgeAssetTypes,pledgeNotificationTypes,pledgePaymentTypes } from "../../services/pledges";
import { companyIdOf,Empty,ErrorBox,Loading,Money,PageTitle } from "./PledgesCorePages";

const handled="تعذر تحميل البيانات، يرجى مراجعة الإعدادات أو الاتصال.";
const useRows=(loader,deps=[])=>{const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{const x=await loader();setRows(Array.isArray(x)?x:[]);setError("")}catch(e){console.error("Pledges page error",e);setRows([]);setError(handled)}finally{setLoading(false)}};useEffect(()=>{load()},deps);return{rows,loading,error,load}};
const Table=({headers=[],rows=[],render})=>rows.length?<div className="panel overflow-x-auto p-4"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table></div>:<Empty/>;
const OperationalNote=()=> <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4 text-sm font-bold text-violet-800">هذه الوحدة تشغيلية لإدارة الرهون العينية ولا تقوم بإنشاء قيود محاسبية تلقائية.</div>;
const printTemplate=(title,content)=>{try{const w=window.open("","_blank");if(!w)throw new Error("تعذر فتح نافذة الطباعة");w.document.write(`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Tahoma,Arial,sans-serif;padding:35px;line-height:2;color:#172033}h1{color:#312e81;border-bottom:2px solid #312e81;padding-bottom:12px}.box{border:1px solid #cbd5e1;border-radius:10px;padding:14px;margin:12px 0}.sign{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:50px}</style></head><body><h1>${title}</h1>${content}<div class="sign"><div>توقيع العميل:</div><div>توقيع الموظف:</div><div>اعتماد الإدارة:</div></div></body></html>`);w.document.close();w.focus();w.print()}catch(e){console.error("Pledge print error",e)}};

export function PledgeVaultPage(props={}){
 const companyId=companyIdOf(props),assets=useRows(()=>pledgesService.getVaultAssetsReport(companyId),[companyId]),locations=useRows(()=>pledgesService.listStorageLocations(companyId),[companyId]),[form,setForm]=useState({branch:"",vault_no:"",shelf_no:"",bag_no:"",location_description:""}),[message,setMessage]=useState("");
 const add=async()=>{try{await pledgesService.createStorageLocation(companyId,form);setMessage("تمت إضافة موقع الحفظ.");locations.load()}catch(e){console.error("Storage location error",e);setMessage("تعذر حفظ موقع التخزين.")}};
 const move=async(row)=>{const location=locations.rows[0];if(!location)return setMessage("أضف موقع تخزين أولًا.");try{await pledgesService.updatePledgeAsset(companyId,row.asset_id,{storage_location_id:location.location_id,vault_no:location.vault_no,shelf_no:location.shelf_no,bag_no:location.bag_no});setMessage("تم نقل الأصل وتسجيل الحركة.");assets.load()}catch(e){console.error("Vault movement error",e);setMessage("تعذر نقل الأصل.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="خزنة الرهون"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<ErrorBox text={assets.error}/><div className="panel grid gap-3 p-4 md:grid-cols-5">{["branch","vault_no","shelf_no","bag_no","location_description"].map((k,i)=><input key={k} className="field" placeholder={["الفرع","الخزنة","الرف","الكيس","وصف الموقع"][i]} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button className="btn-primary" onClick={add}>إضافة موقع تخزين</button></div>{assets.loading?<Loading/>:<Table headers={["رقم الرهن","نوع الأصل","الوصف","الخزنة","الرف","الكيس","حالة الأصل","إجراء"]} rows={assets.rows} render={x=><tr key={x.asset_id}><td>{x.pledge_id}</td><td>{x.asset_type}</td><td>{x.asset_description}</td><td>{x.vault_no}</td><td>{x.shelf_no}</td><td>{x.bag_no}</td><td>{x.asset_status}</td><td><button className="btn-secondary !h-8" onClick={()=>move(x)}>نقل إلى الموقع المحدد</button></td></tr>}/>}</div>;
}

export function PledgeRedemptionPage(props={}){
 const companyId=companyIdOf(props),[search,setSearch]=useState(""),[pledge,setPledge]=useState(null),[balance,setBalance]=useState(null),[amount,setAmount]=useState(0),[message,setMessage]=useState("");
 const find=async()=>{try{const rows=await pledgesService.listPledges(companyId);const x=rows.find(r=>r.pledge_no===search||r.pledge_id===search)||null;setPledge(x);setBalance(x?await pledgesService.calculatePledgeBalance(companyId,x.pledge_id):null);if(!x)setMessage("لم يتم العثور على الرهن.")}catch(e){console.error("Redemption search error",e);setMessage(handled)}};
 const pay=async(full=false)=>{if(!pledge)return;try{const value=full?Number(balance?.remaining_amount||0):Number(amount||0);await pledgesService.createPledgePayment(companyId,{pledge_id:pledge.pledge_id,payment_date:new Date().toISOString().slice(0,10),payment_type:full?"سداد كامل":"سداد جزئي",amount:value,received_by:props.currentUser?.username||""});const next=await pledgesService.calculatePledgeBalance(companyId,pledge.pledge_id);setBalance(next);if(next?.remaining_amount<=0){await pledgesService.changePledgeStatus(companyId,pledge.pledge_id,"مفكوك","سداد كامل وفك الرهن");setMessage("تم السداد الكامل وتغيير الحالة إلى مفكوك.")}else setMessage("تم تسجيل الدفعة.")}catch(e){console.error("Pledge payment error",e);setMessage("تعذر تسجيل السداد.")}};
 const release=()=>pledge&&printTemplate("إشعار فك رهن",`<div class="box">رقم الرهن: ${pledge.pledge_no}<br>العميل: ${pledge.customer_name}<br>تم سداد كامل المبلغ وتسليم الأصل للعميل.</div><p>توقيع العميل: __________________</p>`);
 return <div className="space-y-5" dir="rtl"><PageTitle title="السداد وفك الرهن"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel flex gap-3 p-4"><input className="field" placeholder="رقم الرهن" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn-primary" onClick={find}>بحث</button></div>{pledge&&<><div className="grid gap-4 md:grid-cols-4">{[["المبلغ المعتمد",balance?.approved_amount],["الرسوم",balance?.total_fees],["المدفوع",balance?.total_paid],["المتبقي",balance?.remaining_amount]].map(([a,b])=><div className="panel p-5" key={a}><small>{a}</small><b className="block text-xl"><Money value={b}/></b></div>)}</div><div className="panel flex flex-wrap gap-3 p-4"><input type="number" className="field max-w-56" value={amount} onChange={e=>setAmount(e.target.valueAsNumber)}/><button className="btn-secondary" onClick={()=>pay(false)}>إضافة دفعة</button><button className="btn-primary" onClick={()=>pay(true)}>سداد كامل وفك الرهن</button><button className="btn-secondary" onClick={release}>طباعة إشعار فك رهن</button></div></>}</div>;
}

export function PledgeRenewalsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.listPledges(companyId),[companyId]),[message,setMessage]=useState("");
 const renew=async(row)=>{try{const settings=await pledgesService.listPledgeSettings(companyId),setting=settings.find(x=>x.asset_type===row.asset_type)||settings[0]||{};if(Number(row.renewal_count||0)>=Number(setting.max_renewal_count??2))throw new Error("تم بلوغ الحد الأقصى لعدد التمديدات.");const due=new Date(row.due_date);due.setDate(due.getDate()+Number(setting.default_pledge_days||30));await pledgesService.updatePledge(companyId,row.pledge_id,{due_date:due.toISOString().slice(0,10),renewal_count:Number(row.renewal_count||0)+1,status:"ممدد"});await pledgesService.changePledgeStatus(companyId,row.pledge_id,"ممدد","تمديد مدة الرهن");setMessage("تم تمديد الرهن.");data.load()}catch(e){console.error("Pledge renewal error",e);setMessage(e.message||"تعذر التمديد.")}};
 const rows=data.rows.filter(x=>["نشط","مستحق قريبًا","ممدد"].includes(x.status));
 return <div className="space-y-5" dir="rtl"><PageTitle title="التمديد والتجديد"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}{data.loading?<Loading/>:<Table headers={["رقم الرهن","العميل","الاستحقاق","عدد التمديدات","الحالة","إجراء"]} rows={rows} render={x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.due_date}</td><td>{x.renewal_count||0}</td><td>{x.status}</td><td><button className="btn-primary !h-8" onClick={()=>renew(x)}>تمديد 30 يومًا</button></td></tr>}/>}</div>;
}

export function PledgeDefaultsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.getOverduePledgesReport(companyId),[companyId]),[message,setMessage]=useState("");
 const liquidate=async(row)=>{try{await pledgesService.changePledgeStatus(companyId,row.pledge_id,"تحت التصفية","تجاوز تاريخ الاستحقاق");await pledgesService.createDisposal(companyId,{pledge_id:row.pledge_id,disposal_date:new Date().toISOString().slice(0,10),disposal_status:"مسودة",reason:"تعثر الرهن"});setMessage("تم تحويل الرهن إلى التصفية وإنشاء سجل تصرف.");data.load()}catch(e){console.error("Liquidation error",e);setMessage(e.message||"تعذر بدء التصفية.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="التعثر والتصفية"/>{message&&<div className="rounded-xl bg-amber-50 p-3 font-bold text-amber-800">{message}</div>}{data.loading?<Loading/>:<Table headers={["الرهن","العميل","الاستحقاق","أيام التأخير","المتبقي","الحالة","إجراء"]} rows={data.rows} render={x=><tr key={x.pledge_id}><td>{x.pledge_no}</td><td>{x.customer_name}</td><td>{x.due_date}</td><td>{Math.max(0,Math.floor((Date.now()-new Date(x.due_date).getTime())/86400000))}</td><td><Money value={x.remaining_amount}/></td><td>{x.status}</td><td><button className="btn-secondary !h-8" onClick={()=>printTemplate("إشعار تأخير",`<div class="box">العميل: ${x.customer_name}<br>الرهن: ${x.pledge_no}<br>يرجى السداد قبل اتخاذ إجراءات التصفية.</div>`)}>إشعار نهائي</button> <button className="btn-primary !h-8" onClick={()=>liquidate(x)}>تحت التصفية</button></td></tr>}/>}</div>;
}

export function PledgeNotificationsPage(props={}){
 const companyId=companyIdOf(props),due=useRows(()=>pledgesService.getDuePledgesReport(companyId),[companyId]),notifications=useRows(()=>pledgesService.listPledgeNotifications(companyId),[companyId]),[message,setMessage]=useState("");
 const generate=async(row)=>{try{await pledgesService.createPledgeNotification(companyId,{pledge_id:row.pledge_id,customer_id:row.customer_id,notification_type:"تذكير قبل الاستحقاق",notification_date:new Date().toISOString().slice(0,10),message:`تذكير بقرب استحقاق الرهن رقم ${row.pledge_no}`});setMessage("تم إنشاء الإشعار الداخلي.");notifications.load()}catch(e){console.error("Notification error",e);setMessage("تعذر إنشاء الإشعار.")}};
 return <div className="space-y-5" dir="rtl"><PageTitle title="إشعارات الاستحقاق"/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel p-5"><h3 className="mb-3 font-black">رهون مستحقة قريبًا</h3>{due.rows.length?due.rows.map(x=><div className="flex items-center gap-3 border-b py-2" key={x.pledge_id}><span>{x.pledge_no} — {x.customer_name} — {x.due_date}</span><button className="btn-secondary mr-auto !h-8" onClick={()=>generate(x)}>إنشاء تذكير</button></div>):<Empty/>}</div><Table headers={["النوع","التاريخ","الرسالة","الحالة","إجراء"]} rows={notifications.rows} render={x=><tr key={x.notification_id}><td>{x.notification_type}</td><td>{x.notification_date}</td><td>{x.message}</td><td>{x.status}</td><td><button className="btn-primary !h-8" onClick={()=>pledgesService.markNotificationSent(companyId,x.notification_id).then(notifications.load)}>تحديد كمرسل</button></td></tr>}/></div>;
}

export function PledgeReportsPage(props={}){
 const companyId=companyIdOf(props),[type,setType]=useState("active"),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const fn=type==="active"?pledgesService.getActivePledgesReport:type==="due"?pledgesService.getDuePledgesReport:type==="overdue"?pledgesService.getOverduePledgesReport:pledgesService.getVaultAssetsReport;const x=await fn(companyId,{});setRows(Array.isArray(x)?x:[]);setError("")}catch(e){console.error("Pledge report error",e);setError(handled);setRows([])}finally{setLoading(false)}};useEffect(()=>{load()},[companyId,type]);
 const print=()=>printTemplate("تقرير الرهون",`<div class="box">نوع التقرير: ${type}<br>عدد السجلات: ${rows.length}</div>`);
 return <div className="space-y-5" dir="rtl"><PageTitle title="تقارير الرهون"><button className="btn-primary" onClick={print}>طباعة التقرير</button></PageTitle><OperationalNote/><ErrorBox text={error}/><select className="field max-w-sm" value={type} onChange={e=>setType(e.target.value)}><option value="active">الرهون النشطة</option><option value="due">الرهون المستحقة</option><option value="overdue">الرهون المتأخرة</option><option value="vault">الأصول داخل الخزنة</option></select>{loading?<Loading/>:<Table headers={["المعرف","الرهن / الأصل","العميل","الفرع","الحالة","القيمة"]} rows={rows} render={x=><tr key={x.pledge_id||x.asset_id}><td>{x.pledge_id||x.asset_id}</td><td>{x.pledge_no||x.asset_description}</td><td>{x.customer_name||"—"}</td><td>{x.branch||"—"}</td><td>{x.status||x.asset_status}</td><td><Money value={x.approved_amount||x.accepted_pledge_value}/></td></tr>}/>}</div>;
}

export function PledgeSettingsPage(props={}){
 const companyId=companyIdOf(props),data=useRows(()=>pledgesService.listPledgeSettings(companyId),[companyId]),[form,setForm]=useState({asset_type:"ذهب",max_financing_ratio:70,default_pledge_days:30,max_renewal_count:2,reminder_days_before_due:3,default_storage_fee:0,default_valuation_fee:0,default_admin_fee:0,liquidation_after_delay_days:15,require_manager_approval:true,is_active:true}),[message,setMessage]=useState("");
 const save=async()=>{try{await pledgesService.upsertPledgeSetting(companyId,form);setMessage("تم حفظ إعدادات نوع الأصل.");data.load()}catch(e){console.error("Pledge settings error",e);setMessage("تعذر حفظ الإعدادات.")}};
 const F=({k,l})=><label className="text-sm font-bold">{l}<input type="number" className="field mt-1" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.valueAsNumber})}/></label>;
 return <div className="space-y-5" dir="rtl"><PageTitle title="إعدادات الرهون"/><OperationalNote/>{message&&<div className="rounded-xl bg-blue-50 p-3 font-bold">{message}</div>}<div className="panel grid gap-4 p-5 md:grid-cols-3"><label className="text-sm font-bold">نوع الأصل<select className="field mt-1" value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value})}>{pledgeAssetTypes.map(x=><option key={x}>{x}</option>)}</select></label><F k="max_financing_ratio" l="نسبة التمويل القصوى"/><F k="default_pledge_days" l="مدة الرهن الافتراضية"/><F k="max_renewal_count" l="أقصى عدد تمديدات"/><F k="reminder_days_before_due" l="أيام التذكير"/><F k="default_storage_fee" l="رسوم الحفظ"/><F k="default_valuation_fee" l="رسوم التقييم"/><F k="default_admin_fee" l="الرسوم الإدارية"/><F k="liquidation_after_delay_days" l="التصفية بعد أيام"/><label><input type="checkbox" checked={form.require_manager_approval} onChange={e=>setForm({...form,require_manager_approval:e.target.checked})}/> يتطلب اعتماد المدير</label><label><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> مفعل</label><button className="btn-primary" onClick={save}>حفظ</button></div><Table headers={["نوع الأصل","نسبة التمويل","المدة","التمديدات","التذكير","الحالة"]} rows={data.rows} render={x=><tr key={x.setting_id}><td>{x.asset_type}</td><td>{x.max_financing_ratio}%</td><td>{x.default_pledge_days} يوم</td><td>{x.max_renewal_count}</td><td>{x.reminder_days_before_due} أيام</td><td>{x.is_active?"مفعل":"غير مفعل"}</td></tr>}/></div>;
}
