import { supabase } from "./supabase";

const now=()=>new Date().toISOString(), today=()=>now().slice(0,10);
const makeId=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;
const company=value=>{const id=String(value||"").trim();if(!id)throw new Error("معرّف الشركة مطلوب.");return id};
const safeList=async(table,companyId,filters={})=>{try{let q=supabase.from(table).select("*").eq("company_id",company(companyId));Object.entries(filters||{}).forEach(([k,v])=>{if(v!==""&&v!==null&&v!==undefined&&v!=="all")q=q.eq(k,v)});const{data,error}=await q.order("created_at",{ascending:false});if(error)throw error;return Array.isArray(data)?data:[]}catch(error){console.error(`Advances list error (${table})`,error);return[]}};
const one=async(table,companyId,key,value)=>{try{const{data,error}=await supabase.from(table).select("*").eq("company_id",company(companyId)).eq(key,value).maybeSingle();if(error)throw error;return data||null}catch(error){console.error(`Advances single error (${table})`,error);return null}};
const insert=async(table,prefix,key,companyId,payload={})=>{const row={...payload,company_id:company(companyId),[key]:payload[key]||makeId(prefix),created_at:payload.created_at||now(),updated_at:now()};const{data,error}=await supabase.from(table).insert(row).select().single();if(error)throw error;return data||row};
const update=async(table,key,companyId,id,payload={})=>{const clean={...payload,updated_at:now()};delete clean.company_id;delete clean[key];delete clean.created_at;const{data,error}=await supabase.from(table).update(clean).eq("company_id",company(companyId)).eq(key,id).select().single();if(error)throw error;return data};
const audit=async(companyId,entity,id,action,newData,oldData=null,reason="")=>{try{await supabase.from("advance_audit_logs").insert({audit_id:makeId("audit"),company_id:company(companyId),entity_name:entity,entity_id:id,action_type:action,new_data:newData,old_data:oldData,action_by:newData?.action_by||newData?.created_by||"",action_at:now(),reason})}catch(e){console.error("Advance audit error",e)}};
const logStatus=async(companyId,advanceId,oldStatus,newStatus,actionBy="",reason="")=>{try{await supabase.from("advance_status_logs").insert({log_id:makeId("log"),company_id:company(companyId),advance_id:advanceId,old_status:oldStatus,new_status:newStatus,action_by:actionBy,action_at:now(),reason})}catch(e){console.error("Advance status log error",e)}};
export const listAdvanceParties=(c,f={})=>safeList("advance_parties",c,f);
export const createAdvanceParty=async(c,p)=>{if(!String(p?.party_name||"").trim())throw new Error("اسم صاحب السلفة مطلوب.");const keys=["party_id","party_type","party_name","employee_id","customer_id","supplier_id","branch","department","job_title","phone","identity_number","address","monthly_salary","risk_level","is_active","notes"],clean=Object.fromEntries(keys.filter(k=>p?.[k]!==undefined).map(k=>[k,p[k]]));const r=await insert("advance_parties","party","party_id",c,clean);await audit(c,"advance_parties",r.party_id,"create",r);return r};
export const updateAdvanceParty=(c,id,p)=>update("advance_parties","party_id",c,id,p);
export const listAdvances=(c,f={})=>safeList("advances",c,f);
export const getAdvanceById=(c,id)=>one("advances",c,"advance_id",id);
export const createAdvance=async(c,p)=>{if(!(Number(p?.request_amount)>0))throw new Error("مبلغ السلفة يجب أن يكون أكبر من صفر.");const keys=["advance_id","advance_no","party_id","party_type","party_name","branch","department","request_date","approval_date","disbursement_date","first_installment_date","advance_type","request_amount","approved_amount","disbursed_amount","total_paid","remaining_amount","installment_count","installment_amount","repayment_method","reason","guarantee_type","guarantee_description","guarantee_value","status","approval_status","approved_by","disbursed_by","created_by","notes"],clean=Object.fromEntries(keys.filter(k=>p?.[k]!==undefined).map(k=>[k,p[k]]));const r=await insert("advances","advance","advance_id",c,{...clean,advance_no:p.advance_no||`ADV-${Date.now()}`,remaining_amount:Number(p.remaining_amount??p.approved_amount??0)});await audit(c,"advances",r.advance_id,"create",r);return r};
export const updateAdvance=async(c,id,p)=>{const old=await getAdvanceById(c,id),r=await update("advances","advance_id",c,id,p);await audit(c,"advances",id,"update",r,old);return r};
export const changeAdvanceStatus=async(c,id,newStatus,reason="",actionBy="")=>{const old=await getAdvanceById(c,id);if(!old)throw new Error("تعذر العثور على السلفة.");const r=await updateAdvance(c,id,{status:newStatus});await logStatus(c,id,old.status,newStatus,actionBy,reason);return r};
export const cancelAdvance=(c,id,reason)=>changeAdvanceStatus(c,id,"ملغية",reason);
export const createAdvanceApproval=(c,p)=>insert("advance_approvals","approval","approval_id",c,p);
export const listAdvanceApprovals=(c,id)=>safeList("advance_approvals",c,id?{advance_id:id}:{});
export const updateAdvanceApproval=(c,id,p)=>update("advance_approvals","approval_id",c,id,p);
export const approveAdvance=async(c,id,by)=>{const old=await getAdvanceById(c,id);if(!old||["مرفوضة","ملغية"].includes(old.status))throw new Error("لا يمكن اعتماد هذه السلفة.");await createAdvanceApproval(c,{advance_id:id,approver_name:by,approval_status:"معتمد",approval_date:today()});await updateAdvance(c,id,{approval_status:"معتمد",approval_date:today(),approved_by:by});return changeAdvanceStatus(c,id,"معتمدة","اعتماد السلفة",by)};
export const rejectAdvance=async(c,id,by,reason)=>{await createAdvanceApproval(c,{advance_id:id,approver_name:by,approval_status:"مرفوض",approval_date:today(),rejection_reason:reason});await updateAdvance(c,id,{approval_status:"مرفوض"});return changeAdvanceStatus(c,id,"مرفوضة",reason,by)};
export const generateInstallmentSchedule=async(c,id,options={})=>{const a=await getAdvanceById(c,id);if(!a)throw new Error("السلفة غير موجودة.");const count=Math.max(1,Number(options.count||a.installment_count||1)),amount=Number(options.amount||a.disbursed_amount||a.approved_amount||0),first=new Date(options.firstDate||a.first_installment_date);if(Number.isNaN(first.getTime()))throw new Error("تاريخ أول قسط مطلوب.");const rows=[];for(let i=0;i<count;i++){const d=new Date(first);d.setMonth(d.getMonth()+i);const value=i===count-1?amount-(Math.floor(amount/count)*100/100)*(count-1):Math.floor(amount/count*100)/100;rows.push({installment_id:makeId("installment"),company_id:company(c),advance_id:id,installment_no:i+1,due_date:d.toISOString().slice(0,10),installment_amount:value,paid_amount:0,remaining_amount:value,status:"غير مستحق",created_at:now(),updated_at:now()})}const{error}=await supabase.from("advance_installments").insert(rows);if(error)throw error;await audit(c,"advance_installments",id,"generate",rows);return rows};
export const disburseAdvance=async(c,id,by,payload={})=>{const a=await getAdvanceById(c,id);if(!a||a.approval_status!=="معتمد")throw new Error("لا يمكن صرف سلفة غير معتمدة.");const amount=Number(payload.disbursed_amount||a.approved_amount||0);const r=await updateAdvance(c,id,{...payload,disbursed_amount:amount,remaining_amount:amount,disbursement_date:payload.disbursement_date||today(),disbursed_by:by});await changeAdvanceStatus(c,id,a.repayment_method==="أقساط"?"قيد السداد":"مصروفة","صرف السلفة",by);if(a.repayment_method==="أقساط")await generateInstallmentSchedule(c,id,{count:a.installment_count,amount,firstDate:a.first_installment_date});return r};
export const listAdvanceInstallments=(c,id)=>safeList("advance_installments",c,id?{advance_id:id}:{});
export const updateInstallment=(c,id,p)=>update("advance_installments","installment_id",c,id,p);
export const listAdvancePayments=(c,id)=>safeList("advance_payments",c,id?{advance_id:id}:{});
export const calculateAdvanceBalance=async(c,id)=>{const a=await getAdvanceById(c,id),payments=await listAdvancePayments(c,id);if(!a)return null;const total_paid=payments.reduce((n,x)=>n+Number(x.amount||0),0),remaining_amount=Math.max(0,Number(a.disbursed_amount||a.approved_amount||0)-total_paid);return{...a,total_paid,remaining_amount}};
export const createAdvancePayment=async(c,p)=>{const a=await getAdvanceById(c,p.advance_id);if(!a||["ملغية","مرفوضة"].includes(a.status))throw new Error("لا يمكن تحصيل دفعة لهذه السلفة.");const row=await insert("advance_payments","payment","payment_id",c,{...p,amount:Number(p.amount||0)});if(p.installment_id){const i=await one("advance_installments",c,"installment_id",p.installment_id);if(i){const paid=Number(i.paid_amount||0)+Number(p.amount||0),remaining=Math.max(0,Number(i.installment_amount||0)-paid);await updateInstallment(c,i.installment_id,{paid_amount:paid,remaining_amount:remaining,payment_date:p.payment_date,status:remaining<=0?"مدفوع":"مدفوع جزئيًا"})}}const b=await calculateAdvanceBalance(c,p.advance_id);await updateAdvance(c,p.advance_id,{total_paid:b.total_paid,remaining_amount:b.remaining_amount});if(b.remaining_amount<=0)await changeAdvanceStatus(c,p.advance_id,"مسددة بالكامل","اكتمال السداد",p.received_by);await audit(c,"advance_payments",row.payment_id,"create",row);return row};
export const listAdvanceNotifications=(c,f={})=>safeList("advance_notifications",c,f);
export const createAdvanceNotification=(c,p)=>insert("advance_notifications","notification","notification_id",c,p);
export const markAdvanceNotificationSent=(c,id)=>update("advance_notifications","notification_id",c,id,{status:"مرسل",sent_at:now()});
const dueRows=async(c,overdue=false)=>{const advances=await listAdvances(c),installments=await safeList("advance_installments",c),byId=new Map(advances.map(x=>[x.advance_id,x])),limit=new Date(Date.now()+7*86400000).toISOString().slice(0,10);return installments.filter(x=>Number(x.remaining_amount)>0&&(overdue?x.due_date<today():x.due_date>=today()&&x.due_date<=limit)).map(x=>({...x,advance:byId.get(x.advance_id)||{}}))};
export const getActiveAdvancesReport=async(c)=> (await listAdvances(c)).filter(x=>!["مسددة بالكامل","مرفوضة","ملغية"].includes(x.status));
export const getDueInstallmentsReport=c=>dueRows(c,false);
export const getOverdueAdvancesReport=c=>dueRows(c,true);
export const getSettledAdvancesReport=async c=>(await listAdvances(c)).filter(x=>x.status==="مسددة بالكامل");
export const getAdvancesByPartyReport=(c,f={})=>listAdvances(c,f);
export const getAdvancesDashboardStats=async c=>{const rows=await listAdvances(c),due=await getDueInstallmentsReport(c),overdue=await getOverdueAdvancesReport(c);const active=rows.filter(x=>!["مسددة بالكامل","مرفوضة","ملغية"].includes(x.status));return{active_count:active.length,disbursed:rows.reduce((n,x)=>n+Number(x.disbursed_amount||0),0),paid:rows.reduce((n,x)=>n+Number(x.total_paid||0),0),remaining:rows.reduce((n,x)=>n+Number(x.remaining_amount||0),0),pending:rows.filter(x=>x.approval_status==="بانتظار الاعتماد").length,due:due.length,overdue:overdue.length}};
export const listAdvanceSettings=c=>safeList("advance_settings",c);
export const upsertAdvanceSetting=async(c,p)=>{const row={...p,company_id:company(c),setting_id:p.setting_id||makeId("setting"),updated_at:now()};const{data,error}=await supabase.from("advance_settings").upsert(row,{onConflict:"setting_id"}).select().single();if(error)throw error;return data||row};

export const createExistingAdvance=async(c,payload={})=>{
 const original=Number(payload.original_amount||0),paid=Number(payload.previously_paid||0),remaining=Math.max(0,Number(payload.current_remaining??original-paid));
 if(!String(payload.party_name||"").trim())throw new Error("اسم صاحب السلفة مطلوب.");
 if(!(original>0))throw new Error("المبلغ الأصلي يجب أن يكون أكبر من صفر.");
 const party=await createAdvanceParty(c,payload);
 const status=remaining<=0?"مسددة بالكامل":payload.status||"قيد السداد";
 const advance=await createAdvance(c,{...payload,party_id:party.party_id,advance_no:payload.old_advance_no||undefined,request_date:payload.disbursement_date||today(),approval_date:payload.disbursement_date||today(),disbursement_date:payload.disbursement_date||today(),request_amount:original,approved_amount:original,disbursed_amount:original,total_paid:paid,remaining_amount:remaining,approval_status:"معتمد",status,created_by:payload.created_by||"",notes:[payload.notes,"تم إدخال هذه السلفة كسلفة سابقة عند تهيئة النظام."].filter(Boolean).join(" ")});
 await logStatus(c,advance.advance_id,"",status,payload.created_by||"","تم إدخال سلفة سابقة");
 if(remaining>0&&Number(payload.remaining_installment_count||payload.installment_count||0)>0){
  if(payload.schedule_mode==="manual"&&Array.isArray(payload.manual_installments)&&payload.manual_installments.length){
   const rows=payload.manual_installments.map((x,i)=>({installment_id:makeId("installment"),company_id:company(c),advance_id:advance.advance_id,installment_no:Number(x.installment_no||i+1),due_date:x.due_date,installment_amount:Number(x.installment_amount||0),paid_amount:Number(x.paid_amount||0),remaining_amount:Number(x.remaining_amount??x.installment_amount??0),status:x.status||"غير مستحق",notes:x.notes||"",created_at:now(),updated_at:now()}));
   const{error}=await supabase.from("advance_installments").insert(rows);if(error)throw error;await audit(c,"advance_installments",advance.advance_id,"existing_manual_schedule",rows);
  }else await generateInstallmentSchedule(c,advance.advance_id,{count:Number(payload.remaining_installment_count||payload.installment_count),amount:remaining,firstDate:payload.first_installment_date});
 }
 return advance;
};
export const advancesService={createExistingAdvance,listAdvanceParties,createAdvanceParty,updateAdvanceParty,listAdvances,getAdvanceById,createAdvance,updateAdvance,cancelAdvance,approveAdvance,rejectAdvance,disburseAdvance,changeAdvanceStatus,generateInstallmentSchedule,listAdvanceInstallments,updateInstallment,listAdvancePayments,createAdvancePayment,calculateAdvanceBalance,listAdvanceApprovals,createAdvanceApproval,updateAdvanceApproval,listAdvanceNotifications,createAdvanceNotification,markAdvanceNotificationSent,getAdvancesDashboardStats,getActiveAdvancesReport,getDueInstallmentsReport,getOverdueAdvancesReport,getSettledAdvancesReport,getAdvancesByPartyReport,listAdvanceSettings,upsertAdvanceSetting};
export default advancesService;
