import { supabase } from "./supabase";
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const required=c=>{if(!String(c||"").trim())throw Error("company_id is required.")};
export const defaultAttendanceKpiRules={attendance_weight_percent:15,max_late_minutes_without_penalty:0,late_penalty_per_occurrence:0,late_penalty_per_minute:0,absence_penalty:0,early_leave_penalty:0,approved_leave_neutral_enabled:true,unauthorized_absence_exclusion_enabled:false,max_absence_days_before_incentive_block:0,max_late_occurrences_before_incentive_reduction:0,overtime_bonus_enabled:false,overtime_bonus_points:0,minimum_attendance_score_for_incentive:0};
export const calculateAttendanceScore=(records=[],rules={})=>{const r={...defaultAttendanceKpiRules,...rules};const late=records.filter(x=>num(x.late_minutes)>num(r.max_late_minutes_without_penalty));const absent=records.filter(x=>x.is_absent&&!((x.is_approved_leave||x.status==="\u0625\u062c\u0627\u0632\u0629 \u0645\u0639\u062a\u0645\u062f\u0629")&&r.approved_leave_neutral_enabled));const early=records.filter(x=>num(x.early_leave_minutes)>0);const overtime=records.reduce((s,x)=>s+num(x.overtime_minutes),0);const penalty=late.length*num(r.late_penalty_per_occurrence)+late.reduce((s,x)=>s+Math.max(0,num(x.late_minutes)-num(r.max_late_minutes_without_penalty))*num(r.late_penalty_per_minute),0)+absent.length*num(r.absence_penalty)+early.length*num(r.early_leave_penalty);const bonus=r.overtime_bonus_enabled&&overtime>0?num(r.overtime_bonus_points):0;return Math.max(0,Math.min(100,Number((100-penalty+bonus).toFixed(2))))};
const aggregate=(records,rules,month,year)=>Object.values(records.reduce((acc,row)=>{const k=String(row.employee_id);if(!acc[k])acc[k]={company_id:row.company_id,period_month:num(month),period_year:num(year),employee_id:k,employee_name:row.employee_name,branch:row.branch,job_title:row.job_title,rows:[]};acc[k].rows.push(row);return acc},{})).map(g=>({...g,score_id:`attendance-score-${g.company_id}-${year}-${month}-${g.employee_id}`,total_work_days:g.rows.length,present_days:g.rows.filter(x=>!x.is_absent&&!x.is_rest_day).length,absent_days:g.rows.filter(x=>x.is_absent&&!x.is_approved_leave).length,approved_leave_days:g.rows.filter(x=>x.is_approved_leave).length,late_occurrences:g.rows.filter(x=>num(x.late_minutes)>0).length,total_late_minutes:g.rows.reduce((s,x)=>s+num(x.late_minutes),0),early_leave_occurrences:g.rows.filter(x=>num(x.early_leave_minutes)>0).length,total_early_leave_minutes:g.rows.reduce((s,x)=>s+num(x.early_leave_minutes),0),overtime_minutes:g.rows.reduce((s,x)=>s+num(x.overtime_minutes),0),attendance_score:calculateAttendanceScore(g.rows,rules),max_score:100,calculated_at:new Date().toISOString(),rows:undefined,updated_at:new Date().toISOString()}));
export const attendanceKpiService={
 async loadAttendanceKpiRules(companyId){required(companyId);const rows=await supabase.select("performance_attendance_kpi_rules",`select=*&company_id=eq.${encodeURIComponent(companyId)}&limit=1`);return rows[0]||null},
 async saveAttendanceKpiRules(payload){required(payload.company_id);const row={...defaultAttendanceKpiRules,...payload,rule_id:payload.rule_id||`attendance-rule-${payload.company_id}`,updated_at:new Date().toISOString()};const{data,error}=await supabase.from("performance_attendance_kpi_rules").upsert(row,{onConflict:"company_id"}).select().single();if(error)throw error;return data},
 calculateAttendanceScore,
 async calculateMonthlyAttendanceScores(companyId,month,year){required(companyId);const from=`${year}-${String(month).padStart(2,"0")}-01`;const last=new Date(Number(year),Number(month),0).getDate();const to=`${year}-${String(month).padStart(2,"0")}-${last}`;const [rules,records]=await Promise.all([this.loadAttendanceKpiRules(companyId),supabase.select("hr_attendance_daily_records",`select=*&company_id=eq.${encodeURIComponent(companyId)}&attendance_date=gte.${from}&attendance_date=lte.${to}&approval_status=eq.approved`)]);if(!rules)throw Error("\u0644\u0645 \u064a\u062a\u0645 \u0636\u0628\u0637 \u0642\u0648\u0627\u0639\u062f \u0627\u0644\u062d\u0636\u0648\u0631 \u0648\u0627\u0644\u0627\u0646\u0636\u0628\u0627\u0637 \u0628\u0639\u062f.");return aggregate(records,rules,month,year)},
 async saveAttendanceScores(companyId,scores){required(companyId);const rows=scores.map(x=>({...x,company_id:companyId}));return rows.length?supabase.upsert("performance_attendance_scores",rows,{onConflict:"company_id,period_month,period_year,employee_id"}):[]},
 async loadAttendanceScores(companyId,filters={}){required(companyId);const p=["select=*",`company_id=eq.${encodeURIComponent(companyId)}`];for(const[k,v]of Object.entries(filters))if(v!==""&&v!=null)p.push(`${k}=eq.${encodeURIComponent(v)}`);return supabase.select("performance_attendance_scores",p.join("&"))},
 async syncAttendanceScoresToKpi(companyId,month,year){const scores=await this.loadAttendanceScores(companyId,{period_month:month,period_year:year});return{synced:scores.length,scores}},
 async syncEmployeeAttendanceEventsToRecords(companyId,fromDate,toDate){required(companyId);const events=await supabase.select("employee_attendance_events",`select=*&company_id=eq.${encodeURIComponent(companyId)}&attendance_date=gte.${fromDate}&attendance_date=lte.${toDate}&order=event_time.asc`);const grouped={};for(const e of events){const k=e.employee_id+"|"+e.attendance_date;(grouped[k]??=[]).push(e)}const rows=Object.values(grouped).map(es=>{const cin=es.find(e=>e.event_type==="check_in"),cout=[...es].reverse().find(e=>e.event_type==="check_out");return{attendance_id:`employee-app-${companyId}-${cin?.employee_id||es[0].employee_id}-${es[0].attendance_date}`,company_id:companyId,employee_id:es[0].employee_id,employee_name:es[0].employee_name,attendance_date:es[0].attendance_date,check_in_time:cin?.event_time||null,check_out_time:cout?.event_time||null,source:"employee_app",approval_status:"draft",raw_payload:{events:es},updated_at:new Date().toISOString()}});return rows.length?supabase.upsert("hr_attendance_daily_records",rows,{onConflict:"company_id,employee_id,attendance_date"}):[]}
};
export const {loadAttendanceKpiRules,saveAttendanceKpiRules,calculateMonthlyAttendanceScores,saveAttendanceScores,loadAttendanceScores,syncAttendanceScoresToKpi,syncEmployeeAttendanceEventsToRecords}=attendanceKpiService;
