
import {supabase}from"./supabase";
const company=v=>String(v||"").trim(),num=v=>Number(v||0),arr=v=>Array.isArray(v)?v:[];
const select=async(table,companyId,order="created_at.desc")=>{if(!company(companyId))return{rows:[],errorMessage:"لم يتم تحديد الشركة الحالية"};try{const rows=await supabase.select(table,`select=*&company_id=eq.${encodeURIComponent(companyId)}&order=${order}`);return{rows:arr(rows),errorMessage:""}}catch(error){console.error(`HR reports source error (${table})`,error);return{rows:[],errorMessage:"مصدر بيانات هذا التقرير غير متوفر حالياً"}}};
const dateRange=(row,f={})=>{const d=String(row.operation_date||row.attendance_date||row.date||row.request_date||"");return(!f.fromDate||d>=f.fromDate)&&(!f.toDate||d<=f.toDate)};
const match=(row,f={})=>(!f.branch||String(row.branch||row.branch_name||"")===f.branch)&&(!f.employee_id||String(row.employee_id||row.id||"")===String(f.employee_id))&&(!f.employee_name||String(row.employee_name||row.name||"").includes(f.employee_name))&&(!f.operation_type||String(row.operation_type||"")===f.operation_type)&&(!f.status||f.status==="all"||String(row.status||"")===f.status)&&(!f.search||Object.values(row||{}).join(" ").toLowerCase().includes(String(f.search).toLowerCase()));
const operationCount=r=>num(r.operation_count??r.count??r.total_operations??r.transactions_count??r.processed_count);
const normalizeOp=r=>({operation_date:r.operation_date||r.date||"",employee_id:r.employee_id||"",employee_name:r.employee_name||r.name||"",branch:r.branch||r.branch_name||"",department:r.department||r.department_name||"",job_title:r.job_title||r.job||"",operation_type:r.operation_type||"غير محدد",service_channel:r.service_channel||"",operation_count:operationCount(r),amount:num(r.amount),status:r.status||"",notes:r.notes||""});
const loadOps=async(companyId,filters={})=>{let result=await select("daily_operations",companyId,"operation_date.asc");const sourceRows=arr(result.rows),hasIncludedColumn=sourceRows.some(r=>Object.prototype.hasOwnProperty.call(r,"included_in_kpi"));let rows=sourceRows.filter(r=>r.status==="معتمد"&&(!hasIncludedColumn||r.included_in_kpi===true));rows=rows.map(normalizeOp).filter(r=>dateRange(r,filters)&&match(r,filters));return{rows,errorMessage:result.errorMessage}};
export async function getEmployeesReport(c,f={}){const r=await select("employees",c,"name.asc");return{...r,rows:arr(r.rows).filter(x=>match(x,f)).map(x=>({employee_id:x.employee_id||x.id||"",name:x.name||x.employee_name||"",branch:x.branch||x.branch_name||"",job:x.job_title||x.job||x.position||"",department:x.department||x.department_name||"",status:x.status||x.employee_status||"",hire_date:x.hire_date||x.join_date||"",salary:x.salary||x.basic_salary||0,phone:x.phone||x.mobile||""}))}}
export async function getAttendanceReport(c,f={}){const r=await select("hr_attendance_daily_records",c,"attendance_date.desc");return{...r,rows:arr(r.rows).filter(x=>dateRange(x,f)&&match(x,f)).map(x=>({employee_id:x.employee_id,employee_name:x.employee_name||x.name||"",branch:x.branch||"",attendance_date:x.attendance_date||x.date||"",worked_minutes:num(x.worked_minutes),late_minutes:num(x.late_minutes),absence_minutes:num(x.absence_minutes),overtime_minutes:num(x.overtime_minutes),status:x.status||"",approval_status:x.approval_status||""}))}}
export const getEmployeeProductivityReport=loadOps;
export async function getEmployeeProductivitySummary(c,f={}){const r=await loadOps(c,f),map=new Map();r.rows.forEach(x=>{const k=x.employee_id||x.employee_name,e=map.get(k)||{employee_id:x.employee_id,employee_name:x.employee_name||"غير محدد",branch:x.branch,job_title:x.job_title,total_operations:0,dates:new Set(),types:new Map(),first_operation_date:x.operation_date,last_operation_date:x.operation_date};e.total_operations+=x.operation_count;e.dates.add(x.operation_date);e.types.set(x.operation_type,(e.types.get(x.operation_type)||0)+x.operation_count);if(x.operation_date<e.first_operation_date)e.first_operation_date=x.operation_date;if(x.operation_date>e.last_operation_date)e.last_operation_date=x.operation_date;map.set(k,e)});const rows=[...map.values()].map(e=>({...e,working_days_count:e.dates.size,average_operations_per_day:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,top_operation_type:[...e.types.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد",dates:undefined,types:undefined})).sort((a,b)=>b.total_operations-a.total_operations);return{rows,errorMessage:r.errorMessage}}
export async function getBranchProductivitySummary(c,f={}){const r=await loadOps(c,f),map=new Map();r.rows.forEach(x=>{const k=x.branch||"غير محدد",e=map.get(k)||{branch:k,total_operations:0,employees:new Map(),dates:new Set()};e.total_operations+=x.operation_count;e.employees.set(x.employee_id||x.employee_name,(e.employees.get(x.employee_id||x.employee_name)||0)+x.operation_count);e.dates.add(x.operation_date);map.set(k,e)});return{rows:[...map.values()].map(e=>({branch:e.branch,total_operations:e.total_operations,employees_count:e.employees.size,working_days_count:e.dates.size,average_operations_per_employee:e.employees.size?Number((e.total_operations/e.employees.size).toFixed(2)):0,average_operations_per_day:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,top_employee:[...e.employees.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد"})).sort((a,b)=>b.total_operations-a.total_operations),errorMessage:r.errorMessage}}
export async function getDailyProductivitySummary(c,f={}){const r=await loadOps(c,f),map=new Map();r.rows.forEach(x=>{const e=map.get(x.operation_date)||{operation_date:x.operation_date,total_operations:0,employees:new Map(),branches:new Map()};e.total_operations+=x.operation_count;e.employees.set(x.employee_name,(e.employees.get(x.employee_name)||0)+x.operation_count);e.branches.set(x.branch,(e.branches.get(x.branch)||0)+x.operation_count);map.set(x.operation_date,e)});return{rows:[...map.values()].map(e=>({...e,employees_count:e.employees.size,branches_count:e.branches.size,top_employee:[...e.employees.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد",top_branch:[...e.branches.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد",employees:undefined,branches:undefined})).sort((a,b)=>b.operation_date.localeCompare(a.operation_date)),errorMessage:r.errorMessage}}
export async function getMonthlyProductivitySummary(c,f={}){const r=await loadOps(c,f),map=new Map();r.rows.forEach(x=>{const[y,m]=x.operation_date.split("-"),k=`${y}-${m}`,e=map.get(k)||{period_year:y,period_month:m,total_operations:0,employees:new Map(),branches:new Map(),dates:new Set()};e.total_operations+=x.operation_count;e.employees.set(x.employee_name,(e.employees.get(x.employee_name)||0)+x.operation_count);e.branches.set(x.branch,(e.branches.get(x.branch)||0)+x.operation_count);e.dates.add(x.operation_date);map.set(k,e)});return{rows:[...map.values()].map(e=>({...e,employees_count:e.employees.size,branches_count:e.branches.size,average_daily_operations:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,top_employee:[...e.employees.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد",top_branch:[...e.branches.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"غير محدد",employees:undefined,branches:undefined,dates:undefined})).sort((a,b)=>b.period_year-a.period_year||b.period_month-a.period_month),errorMessage:r.errorMessage}}
export async function getPerformanceReport(c,f={}){for(const table of["performance_kpi_scores","kpi_scores","evaluations"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>match(x,f))}}return getEmployeeProductivitySummary(c,f)}
export async function getPayrollReport(c,f={}){for(const table of["payroll_records","hr_payroll"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}const e=await getEmployeesReport(c,f),rows=e.rows.filter(x=>Number(x.salary)>0);return{rows,errorMessage:rows.length?"":"مصدر بيانات الرواتب غير متوفر حالياً"}}
export async function getLeaveReport(c,f={}){for(const table of["hr_leave_requests","leave_requests","employee_leaves"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}return{rows:[],errorMessage:"مصدر بيانات الإجازات غير متوفر حالياً"}}
export async function getTrainingReport(c,f={}){for(const table of["hr_training_programs","training_programs","hr_training"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}return{rows:[],errorMessage:"مصدر بيانات التدريب غير متوفر حالياً"}}
export const hrReportsService={getEmployeesReport,getAttendanceReport,getPerformanceReport,getEmployeeProductivityReport,getEmployeeProductivitySummary,getBranchProductivitySummary,getDailyProductivitySummary,getMonthlyProductivitySummary,getLeaveReport,getPayrollReport,getTrainingReport};
export default hrReportsService;
