
import {supabase}from"./supabase";
import {getApprovedDailyOperations,getEmployeeProductivitySummary as sharedEmployeeSummary,getBranchProductivitySummary as sharedBranchSummary,getDailyProductivitySummary as sharedDailySummary,getMonthlyProductivitySummary as sharedMonthlySummary} from "./productivityReports";
const company=v=>String(v||"").trim(),num=v=>Number(v||0),arr=v=>Array.isArray(v)?v:[];
const select=async(table,companyId,order="created_at.desc")=>{if(!company(companyId))return{rows:[],errorMessage:"لم يتم تحديد الشركة الحالية"};try{const rows=await supabase.select(table,`select=*&company_id=eq.${encodeURIComponent(companyId)}&order=${order}`);return{rows:arr(rows),errorMessage:""}}catch(error){console.error(`HR reports source error (${table})`,error);return{rows:[],errorMessage:"مصدر بيانات هذا التقرير غير متوفر حالياً"}}};
const dateRange=(row,f={})=>{const d=String(row.operation_date||row.attendance_date||row.date||row.request_date||"");return(!f.fromDate||d>=f.fromDate)&&(!f.toDate||d<=f.toDate)};
const match=(row,f={})=>(!f.branch||String(row.branch||row.branch_name||"")===f.branch)&&(!f.employee_id||String(row.employee_id||row.id||"")===String(f.employee_id))&&(!f.employee_name||String(row.employee_name||row.name||"").includes(f.employee_name))&&(!f.operation_type||String(row.operation_type||"")===f.operation_type)&&(!f.status||f.status==="all"||String(row.status||"")===f.status)&&(!f.search||Object.values(row||{}).join(" ").toLowerCase().includes(String(f.search).toLowerCase()));
const operationCount=r=>num(r.operation_count??r.count??r.total_operations??r.transactions_count??r.processed_count);
const normalizeOp=r=>({operation_date:r.operation_date||r.date||"",employee_id:r.employee_id||"",employee_name:r.employee_name||r.name||"",branch:r.branch||r.branch_name||"",department:r.department||r.department_name||"",job_title:r.job_title||r.job||"",operation_type:r.operation_type||"غير محدد",service_channel:r.service_channel||"",operation_count:operationCount(r),amount:num(r.amount),status:r.status||"",notes:r.notes||""});
const loadOps=async(companyId,filters={})=>({rows:await getApprovedDailyOperations(companyId,filters),errorMessage:""});
export async function getEmployeesReport(c,f={}){const r=await select("employees",c,"name.asc");return{...r,rows:arr(r.rows).filter(x=>match(x,f)).map(x=>({employee_id:x.employee_id||x.id||"",name:x.name||x.employee_name||"",branch:x.branch||x.branch_name||"",job:x.job_title||x.job||x.position||"",department:x.department||x.department_name||"",status:x.status||x.employee_status||"",hire_date:x.hire_date||x.join_date||"",salary:x.salary||x.basic_salary||0,phone:x.phone||x.mobile||""}))}}
export async function getAttendanceReport(c,f={}){const r=await select("hr_attendance_daily_records",c,"attendance_date.desc");return{...r,rows:arr(r.rows).filter(x=>dateRange(x,f)&&match(x,f)).map(x=>({employee_id:x.employee_id,employee_name:x.employee_name||x.name||"",branch:x.branch||"",attendance_date:x.attendance_date||x.date||"",worked_minutes:num(x.worked_minutes),late_minutes:num(x.late_minutes),absence_minutes:num(x.absence_minutes),overtime_minutes:num(x.overtime_minutes),status:x.status||"",approval_status:x.approval_status||""}))}}
export const getEmployeeProductivityReport=loadOps;
export async function getEmployeeProductivitySummary(c,f={}){return{rows:await sharedEmployeeSummary(c,f),errorMessage:""}}
export async function getBranchProductivitySummary(c,f={}){return{rows:await sharedBranchSummary(c,f),errorMessage:""}}
export async function getDailyProductivitySummary(c,f={}){return{rows:await sharedDailySummary(c,f),errorMessage:""}}
export async function getMonthlyProductivitySummary(c,f={}){return{rows:await sharedMonthlySummary(c,f),errorMessage:""}}
export async function getPerformanceReport(c,f={}){for(const table of["performance_kpi_scores","kpi_scores","evaluations"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>match(x,f))}}return getEmployeeProductivitySummary(c,f)}
export async function getPayrollReport(c,f={}){for(const table of["payroll_records","hr_payroll"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}const e=await getEmployeesReport(c,f),rows=e.rows.filter(x=>Number(x.salary)>0);return{rows,errorMessage:rows.length?"":"مصدر بيانات الرواتب غير متوفر حالياً"}}
export async function getLeaveReport(c,f={}){for(const table of["hr_leave_requests","leave_requests","employee_leaves"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}return{rows:[],errorMessage:"مصدر بيانات الإجازات غير متوفر حالياً"}}
export async function getTrainingReport(c,f={}){for(const table of["hr_training_programs","training_programs","hr_training"]){const r=await select(table,c);if(r.rows.length)return{...r,rows:r.rows.filter(x=>dateRange(x,f)&&match(x,f))}}return{rows:[],errorMessage:"مصدر بيانات التدريب غير متوفر حالياً"}}
export const hrReportsService={getEmployeesReport,getAttendanceReport,getPerformanceReport,getEmployeeProductivityReport,getEmployeeProductivitySummary,getBranchProductivitySummary,getDailyProductivitySummary,getMonthlyProductivitySummary,getLeaveReport,getPayrollReport,getTrainingReport};
export default hrReportsService;
