import { supabase } from "./supabase";
const required=c=>{if(!String(c||"").trim())throw new Error("company_id is required.")};
export const incentiveControlsService={
 async loadIncentiveExclusions(companyId,filters={}){required(companyId);const p=["select=*",`company_id=eq.${encodeURIComponent(companyId)}`];for(const[k,v]of Object.entries(filters))if(v!==""&&v!=null)p.push(`${k}=eq.${encodeURIComponent(v)}`);return supabase.select("performance_incentive_exclusions",p.join("&")+"&order=updated_at.desc")},
 async saveIncentiveExclusion(payload){required(payload.company_id);if(!String(payload.reason||"").trim())throw new Error("\u0644\u0627 \u064a\u0645\u0643\u0646 \u0627\u0633\u062a\u062b\u0646\u0627\u0621 \u0645\u0648\u0638\u0641 \u0628\u062f\u0648\u0646 \u062a\u062d\u062f\u064a\u062f \u0627\u0644\u0633\u0628\u0628.");const row={...payload,exclusion_id:payload.exclusion_id||`exclusion-${Date.now()}`,updated_at:new Date().toISOString()};const{data,error}=await supabase.from("performance_incentive_exclusions").upsert(row,{onConflict:"exclusion_id"}).select().single();if(error)throw error;return data},
 deleteIncentiveExclusion(id,companyId){required(companyId);return supabase.request(`/rest/v1/performance_incentive_exclusions?exclusion_id=eq.${encodeURIComponent(id)}&company_id=eq.${encodeURIComponent(companyId)}`,{method:"DELETE",prefer:"return=minimal"})},
 applyIncentiveExclusions(rows=[],exclusions=[]){return rows.map(row=>{const x=exclusions.find(e=>String(e.employee_id)===String(row.employee_id)&&e.approval_status==="approved");if(!x)return row;let value=Number(row.final_incentive??row.suggested_bonus??0);if(x.action_type==="exclude")value=0;if(x.action_type==="reduce_percent")value*=Math.max(0,1-Number(x.reduction_percent||0)/100);if(x.action_type==="fixed_deduction")value-=Number(x.deduction_amount||0);if(x.action_type==="manual_adjustment")value+=Number(x.adjustment_amount||0);return{...row,final_incentive:Math.max(0,value),incentive_exclusion:x,audit_note:x.reason}})},
};
export const {loadIncentiveExclusions,saveIncentiveExclusion,deleteIncentiveExclusion,applyIncentiveExclusions}=incentiveControlsService;
