
import {supabase}from"./supabase";
const a=v=>Array.isArray(v)?v:[],n=v=>Number(v||0),clean=v=>String(v||"").trim();
const normalize=r=>({...r,operation_date:r.operation_date||"",employee_id:r.employee_id||"",employee_name:r.employee_name||"",branch:r.branch||"غير محدد",job_title:r.job_title||r.job_name||r.job||"",operation_type:r.operation_type||"عمليات أخرى",service_channel:r.service_channel||"",operation_count:n(r.operation_count??r.count)});
const dateFilters=(f={})=>{let from=f.fromDate||f.day||"",to=f.toDate||f.day||"";if(f.month&&f.year){from=`${f.year}-${String(f.month).padStart(2,"0")}-01`;to=new Date(Number(f.year),Number(f.month),0).toISOString().slice(0,10)}else if(f.month&&String(f.month).includes("-")){const[y,m]=String(f.month).split("-");from=`${y}-${m}-01`;to=new Date(Number(y),Number(m),0).toISOString().slice(0,10)}return{from,to}};
const matches=(r,f={})=>{const{from,to}=dateFilters(f),d=r.operation_date;return(!from||d>=from)&&(!to||d<=to)&&(!f.branch||f.branch==="all"||r.branch===f.branch)&&(!f.employee_id||r.employee_id===f.employee_id)&&(!f.employee_name||r.employee_name.includes(f.employee_name))&&(!f.operation_type||f.operation_type==="all"||r.operation_type===f.operation_type)&&(!f.service_channel||f.service_channel==="all"||r.service_channel===f.service_channel)};
export async function getApprovedDailyOperations(companyId,filters={}){if(!clean(companyId))return[];try{const rows=a(await supabase.select("daily_operations",`select=*&company_id=eq.${encodeURIComponent(companyId)}&status=eq.${encodeURIComponent("معتمد")}&order=operation_date.asc`)),hasIncluded=rows.some(r=>Object.prototype.hasOwnProperty.call(r,"included_in_kpi"));return rows.filter(r=>(!hasIncluded||r.included_in_kpi===true)&&!["ملغي","مسودة","قيد المراجعة","غير معتمد"].includes(r.status)).map(normalize).filter(r=>matches(r,filters))}catch(error){console.error("Approved productivity operations error",error);return[]}}
const breakdown=(map,type,count)=>map.set(type,(map.get(type)||0)+count),object=map=>Object.fromEntries([...map.entries()].sort((x,y)=>y[1]-x[1]));
export async function getEmployeeProductivitySummary(c,f={}){const rows=await getApprovedDailyOperations(c,f),map=new Map();rows.forEach(r=>{const k=[r.employee_id,r.employee_name,r.branch,r.job_title].join("|"),e=map.get(k)||{employee_id:r.employee_id,employee_name:r.employee_name||"غير محدد",branch:r.branch,job_title:r.job_title,total_operations:0,dates:new Set(),operation_breakdown:new Map()};e.total_operations+=r.operation_count;e.dates.add(r.operation_date);breakdown(e.operation_breakdown,r.operation_type,r.operation_count);map.set(k,e)});const branchTotals=rows.reduce((o,r)=>({...o,[r.branch]:(o[r.branch]||0)+r.operation_count}),{});return[...map.values()].map(e=>({...e,working_days_count:e.dates.size,average_operations_per_day:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,operation_breakdown:object(e.operation_breakdown),percentage_of_branch_total:branchTotals[e.branch]?Number((e.total_operations/branchTotals[e.branch]*100).toFixed(2)):0,dates:undefined})).sort((x,y)=>y.total_operations-x.total_operations)}
export async function getBranchProductivitySummary(c,f={}){const rows=await getApprovedDailyOperations(c,f),map=new Map();rows.forEach(r=>{const e=map.get(r.branch)||{branch:r.branch,total_operations:0,employees:new Set(),dates:new Set(),operation_breakdown:new Map(),employeeTotals:new Map()};e.total_operations+=r.operation_count;e.employees.add(r.employee_id||r.employee_name);e.dates.add(r.operation_date);breakdown(e.operation_breakdown,r.operation_type,r.operation_count);e.employeeTotals.set(r.employee_name,(e.employeeTotals.get(r.employee_name)||0)+r.operation_count);map.set(r.branch,e)});return[...map.values()].map(e=>({branch:e.branch,total_operations:e.total_operations,employees_count:e.employees.size,working_days_count:e.dates.size,average_operations_per_employee:e.employees.size?Number((e.total_operations/e.employees.size).toFixed(2)):0,average_operations_per_day:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,operation_breakdown:object(e.operation_breakdown),top_employee:[...e.employeeTotals.entries()].sort((x,y)=>y[1]-x[1])[0]?.[0]||"غير محدد"})).sort((x,y)=>y.total_operations-x.total_operations)}
export async function getBranchProductivityDetailed(c,f={}){const summary=await getBranchProductivitySummary(c,f);return summary.flatMap(b=>Object.entries(b.operation_breakdown).map(([operation_type,operation_count])=>({branch:b.branch,operation_type,operation_count,employees_count:b.employees_count,working_days_count:b.working_days_count,percentage_of_branch_total:b.total_operations?Number((operation_count/b.total_operations*100).toFixed(2)):0})))}
export async function getDailyProductivitySummary(c,f={}){const rows=await getApprovedDailyOperations(c,f),map=new Map();rows.forEach(r=>{const k=f.branch&&f.branch!=="all"?`${r.operation_date}|${r.branch}`:r.operation_date,e=map.get(k)||{operation_date:r.operation_date,branch:f.branch&&f.branch!=="all"?r.branch:"",total_operations:0,branches:new Set(),employees:new Set(),operation_breakdown:new Map()};e.total_operations+=r.operation_count;e.branches.add(r.branch);e.employees.add(r.employee_id||r.employee_name);breakdown(e.operation_breakdown,r.operation_type,r.operation_count);map.set(k,e)});return[...map.values()].map(e=>({...e,branches_count:e.branches.size,employees_count:e.employees.size,operation_breakdown:object(e.operation_breakdown),branches:undefined,employees:undefined})).sort((x,y)=>y.operation_date.localeCompare(x.operation_date))}
export async function getMonthlyProductivitySummary(c,f={}){const rows=await getApprovedDailyOperations(c,f),map=new Map();rows.forEach(r=>{const[y,m]=r.operation_date.split("-"),k=`${y}-${m}${f.branch&&f.branch!=="all"?"|"+r.branch:""}`,e=map.get(k)||{period_year:y,period_month:m,branch:f.branch&&f.branch!=="all"?r.branch:"",total_operations:0,branches:new Set(),employees:new Set(),dates:new Set(),operation_breakdown:new Map()};e.total_operations+=r.operation_count;e.branches.add(r.branch);e.employees.add(r.employee_id||r.employee_name);e.dates.add(r.operation_date);breakdown(e.operation_breakdown,r.operation_type,r.operation_count);map.set(k,e)});return[...map.values()].map(e=>({...e,branches_count:e.branches.size,employees_count:e.employees.size,average_daily_operations:e.dates.size?Number((e.total_operations/e.dates.size).toFixed(2)):0,operation_breakdown:object(e.operation_breakdown),branches:undefined,employees:undefined,dates:undefined})).sort((x,y)=>y.period_year-x.period_year||y.period_month-x.period_month)}
export default{getApprovedDailyOperations,getEmployeeProductivitySummary,getBranchProductivitySummary,getBranchProductivityDetailed,getDailyProductivitySummary,getMonthlyProductivitySummary};
