export const ArabicLabels = {
  appName: "Tamyuz ERP",
  companyFallback: "التميز للأنظمة الذكية",
  searchPlaceholder: "البحث في النظام",
  notifications: "الإشعارات",
  logout: "تسجيل الخروج",
  roles: {
    platformAdmin: "مدير عام النظام",
    admin: "مدير النظام",
    hr: "الموارد البشرية",
    branchManager: "مدير فرع",
    executive: "الإدارة العليا",
    inventory: "مسؤول المخزون",
    employee: "الموظف",
  },
  sidebar: {
    dashboard: "لوحة التحكم",
    employees: "قائمة الموظفين",
    reports: "قسم التقارير",
    requests: "الطلبات",
    performance: "قياس الأداء",
    incentives: "الحوافز",
    attendance: "حساب الدوام",
    salary: "حساب الراتب",
    disciplinary: "المساءلات والإنذارات",
    recruitment: "التوظيف",
    leaves: "الإجازات",
    complaints: "الشكاوى",
    circulars: "التعاميم",
    termination: "إنهاء الخدمة",
    surveys: "الاستبيانات",
    insurance: "التأمينات",
    announcements: "قسم الإعلانات",
    files: "إدارة الملفات",
    training: "التدريب",
    approvals: "الموافقات",
    orgChart: "الهيكل التنظيمي",
    settings: "إعدادات",
    financialSetup: "تهيئة المعلومات المالية",
    templates: "القوالب",
  },
  statuses: {
    active: "نشط",
    inactive: "غير نشط",
    approved: "معتمد",
    pending: "قيد المراجعة",
    rejected: "مرفوض",
  },
  errors: {
    missingCompanyCode: "يجب إدخال كود الشركة",
    invalidLogin: "بيانات الدخول غير صحيحة",
    noCompanyAccess: "لا تملك صلاحية الوصول إلى بيانات هذه الشركة",
  },
};
