export const erpModuleLabels = {
  platform: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظ†طµط©",
  system: "ط§ظ„ظ†ط¸ط§ظ…",
  hr: "ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©",
  inventory: "ط§ظ„ظ…ط®ط§ط²ظ† ظˆط§ظ„ظ…ط®ط²ظˆظ†",
  sales: "ط§ظ„ظ…ط¨ظٹط¹ط§طھ",
  purchasing: "ط§ظ„ظ…ط´طھط±ظٹط§طھ",
  accounting: "ط§ظ„ط­ط³ط§ط¨ط§طھ",
  crm: "CRM",
  assets: "ط§ظ„ط£طµظˆظ„",
  projects: "ط§ظ„ظ…ط´ط§ط±ظٹط¹",
};

export const permissionActionLabels = {
  can_view: "ط¹ط±ط¶",
  can_create: "ط¥ط¶ط§ظپط©",
  can_edit: "طھط¹ط¯ظٹظ„",
  can_delete: "ط­ط°ظپ",
  can_approve: "ط§ط¹طھظ…ط§ط¯",
  can_reject: "ط±ظپط¶",
  can_cancel: "ط¥ظ„ط؛ط§ط،",
  can_post: "طھط±ط­ظٹظ„",
  can_import: "ط§ط³طھظٹط±ط§ط¯",
  can_export: "طھطµط¯ظٹط±",
  can_print: "ط·ط¨ط§ط¹ط©",
  can_configure: "ط¥ط¯ط§ط±ط©",
  can_manage: "ط¥ط¯ط§ط±ط© ظ…طھظ‚ط¯ظ…ط©",
  can_reset_user_password: "ط¥ط¹ط§ط¯ط© ظƒظ„ظ…ط© ط§ظ„ظ…ط±ظˆط±",
  can_override: "طھط¬ط§ظˆط²",
  can_view_financial: "ظ…ط§ظ„ظٹ",
  can_view_sensitive: "ط­ط³ط§ط³",
};

export const standardPermissionActions = Object.keys(permissionActionLabels);

const commonActions = ["can_view", "can_create", "can_edit", "can_delete", "can_export", "can_print"];
const approvalActions = ["can_view", "can_create", "can_edit", "can_delete", "can_approve", "can_reject", "can_cancel", "can_export", "can_print"];
const financialActions = ["can_view", "can_create", "can_edit", "can_approve", "can_export", "can_print", "can_view_financial", "can_view_sensitive"];
const reportActions = ["can_view", "can_export", "can_print"];
const settingsActions = ["can_view", "can_create", "can_edit", "can_delete", "can_configure", "can_export", "can_print"];

const moduleOverrides = {
  companies_admin: "platform",
  inventory: "inventory",
};

const hrPageKeys = new Set([
  "dashboard", "employees", "employees_grid", "employee_effectiveness", "user_activity_logs", "templates", "evaluations", "productivity", "discipline", "incentives", "top", "plans", "reports", "settings",
  "guarantees", "overtime", "shifts", "daily_operations", "performance_criteria", "performance_kpi_scores", "users_permissions", "recruitment",
  "attendance_dashboard", "attendance_records", "bulk_attendance", "attendance_requests", "working_hours_report", "attendance_in_out_report", "monthly_attendance_report", "attendance_period_settings",
  "reports_center", "audit_logs", "hr_home", "hr_employees_full", "hr_reports", "hr_reports_full", "hr_requests_approvals", "hr_requests", "hr_performance_full", "hr_incentives_full",
  "hr_attendance_payroll", "hr_salary", "hr_disciplinary", "hr_recruitment_full", "hr_leaves", "hr_complaints", "hr_circulars", "hr_termination",
  "hr_surveys", "hr_insurance", "hr_announcements", "hr_files", "hr_contracts", "hr_custodies", "hr_training", "hr_approvals", "hr_org_chart", "hr_settings_full",
  "hr_financial_setup", "hr_templates_full", "hr_settings", "employee_app_settings", "ai_assistant", "theme_settings",
]);

const pageActionOverrides = {
  dashboard: ["can_view", "can_export", "can_print"],
  employees: commonActions,
  employees_grid: ["can_view"],
  employee_effectiveness: ["can_view"],
  user_activity_logs: ["can_view", "can_export", "can_print"],
  hr_employees_full: commonActions,
  discipline: approvalActions,
  hr_attendance_payroll: approvalActions,
  hr_salary: financialActions,
  hr_requests_approvals: approvalActions,
  incentives: financialActions,
  hr_incentives_full: financialActions,
  reports: reportActions,
  reports_center: reportActions,
  hr_reports: reportActions,
  settings: settingsActions,
  system_settings: settingsActions,
  hr_settings: settingsActions,
  employee_app_settings: settingsActions,
  users_permissions: settingsActions,
  audit_logs: ["can_view", "can_export", "can_print", "can_view_sensitive"],
  companies_admin: settingsActions,
  evaluations: ["can_view", "can_create", "can_edit", "can_approve", "can_export", "can_print"],
  performance_criteria: settingsActions,
  "performance-monthly-targets": settingsActions,
  "performance-branch-targets": settingsActions,
  "performance-attendance-rules": settingsActions,
  "performance-incentive-exclusions": settingsActions,
  "performance-incentive-proposal": ["can_view", "can_export", "can_print"],
  "performance-process-guide": ["can_view", "can_print"],
  "hr-attendance-records": ["can_view", "can_create", "can_edit", "can_delete", "can_approve", "can_import", "can_export", "can_print"],
  performance_kpi_scores: ["can_view", "can_create", "can_edit", "can_approve", "can_export", "can_print"],
  templates: settingsActions,
  inventory: ["can_view", "can_create", "can_edit", "can_delete", "can_approve", "can_post", "can_import", "can_export", "can_print", "can_view_financial"],
};

// Sidebar hierarchy belongs to the canonical page registry so navigation,
// permissions and routing continue to share the same page keys.
const navigationMetadata = {
  hr_home: { navGroupKey: "hr_dashboard", navGroupLabel: "ظ„ظˆط­ط© ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©", navGroupOrder: 1, navItemOrder: 1 },
  employees: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 1 },
  employees_grid: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 2 },
  employee_effectiveness: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 3 },
  user_activity_logs: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 4 },
  hr_org_chart: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 5 },
  hr_contracts: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 6 },
  hr_files: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 7 },
  guarantees: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 8 },
  hr_custodies: { navGroupKey: "hr_employees", navGroupLabel: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", navGroupOrder: 2, navItemOrder: 9 },
  daily_operations: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 1 },
  daily_operations_reports: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 1.5 },
  discipline: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 2 },
  shifts: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 3 },
  overtime: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 4 },
  overtime_import_export: { navGroupKey: "hr_attendance", navGroupLabel: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 4.5 },
  attendance_dashboard: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 1, navLabel: "ظ„ظˆط­ط© ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…" },
  attendance_records: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 2, navLabel: "طھط³ط¬ظٹظ„ ط­ط¶ظˆط± ظˆط§ظ†طµط±ط§ظپ" },
  bulk_attendance: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 3, navLabel: "طھط­ط¶ظٹط± ط¬ظ…ط§ط¹ظٹ" },
  attendance_requests: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 4, navLabel: "ظ…ط¹ط§ظ„ط¬ط© ط·ظ„ط¨ط§طھ ط§ظ„ط¹ظ…ظ„" },
  working_hours_report: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 5, navLabel: "طھظ‚ط±ظٹط± ط³ط§ط¹ط§طھ ط§ظ„ط§ط´طھط؛ط§ظ„" },
  attendance_in_out_report: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 6, navLabel: "طھظ‚ط±ظٹط± ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط§ظ†طµط±ط§ظپ" },
  monthly_attendance_report: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 7, navLabel: "طھظ‚ط±ظٹط± ط§ظ„ط­ط¶ظˆط± ط§ظ„ط´ظ‡ط±ظٹ" },
  attendance_period_settings: { navGroupKey: "attendance_calculation", navGroupLabel: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", navGroupOrder: 3, navItemOrder: 8, navLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ ظپطھط±ط§طھ ط§ظ„ط¯ظˆط§ظ…" },
  hr_leaves: { navGroupKey: "hr_requests", navGroupLabel: "ط§ظ„ط¥ط¬ط§ط²ط§طھ ظˆط§ظ„ط·ظ„ط¨ط§طھ", navGroupOrder: 4, navItemOrder: 1 },
  hr_requests_approvals: { navGroupKey: "hr_requests", navGroupLabel: "ط§ظ„ط¥ط¬ط§ط²ط§طھ ظˆط§ظ„ط·ظ„ط¨ط§طھ", navGroupOrder: 4, navItemOrder: 2 },
  hr_salary: { navGroupKey: "hr_payroll", navGroupLabel: "ط§ظ„ط±ظˆط§طھط¨ ظˆط§ظ„ظ…ط²ط§ظٹط§", navGroupOrder: 5, navItemOrder: 1, navLabel: "ط§ظ„ط±ظˆط§طھط¨" },
  hr_financial_setup: { navGroupKey: "hr_payroll", navGroupLabel: "ط§ظ„ط±ظˆط§طھط¨ ظˆط§ظ„ظ…ط²ط§ظٹط§", navGroupOrder: 5, navItemOrder: 2, navLabel: "طھظ‡ظٹط¦ط© ط§ظ„ط¹ظ…ظ„ظٹط§طھ ط§ظ„ظ…ط§ظ„ظٹط©" },
  templates: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 1 },
  evaluations: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 2 },
  performance_criteria: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 3 },
  "performance-monthly-targets": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 4 },
  "performance-branch-targets": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 5 },
  "performance-attendance-rules": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 6 },
  "performance-incentive-exclusions": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 11 },
  "performance-incentive-proposal": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 12 },
  "performance-process-guide": { navGroupKey: "hr_performance", navGroupLabel: "الأداء والحوافز", navGroupOrder: 6, navItemOrder: 13 },
  "hr-attendance-records": { navGroupKey: "hr_attendance", navGroupLabel: "الموارد البشرية", navGroupOrder: 3, navItemOrder: 2.5 },
  performance_kpi_scores: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 7},
  kpi_settings: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 8},
  productivity: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 9},
  incentives: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 10},
  top: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 14},
  plans: { navGroupKey: "hr_performance", navGroupLabel: "ط§ظ„ط£ط¯ط§ط، ظˆط§ظ„ط­ظˆط§ظپط²", navGroupOrder: 6, navItemOrder: 15},
  recruitment: { navGroupKey: "hr_recruitment", navGroupLabel: "ط§ظ„طھظˆط¸ظٹظپ ظˆط§ظ„طھط·ظˆظٹط±", navGroupOrder: 7, navItemOrder: 1, navLabel: "ط§ظ„طھظˆط¸ظٹظپ" },
  hr_training: { navGroupKey: "hr_recruitment", navGroupLabel: "ط§ظ„طھظˆط¸ظٹظپ ظˆط§ظ„طھط·ظˆظٹط±", navGroupOrder: 7, navItemOrder: 2 },
  hr_disciplinary: { navGroupKey: "hr_relations", navGroupLabel: "ط§ظ„ط¹ظ„ط§ظ‚ط§طھ ط§ظ„ظˆط¸ظٹظپظٹط©", navGroupOrder: 8, navItemOrder: 1, navLabel: "ط§ظ„ظ…ط®ط§ظ„ظپط§طھ ظˆط§ظ„ط¥ظ†ط°ط§ط±ط§طھ" },
  hr_circulars: { navGroupKey: "hr_relations", navGroupLabel: "ط§ظ„ط¹ظ„ط§ظ‚ط§طھ ط§ظ„ظˆط¸ظٹظپظٹط©", navGroupOrder: 8, navItemOrder: 2 },
  hr_complaints: { navGroupKey: "hr_relations", navGroupLabel: "ط§ظ„ط¹ظ„ط§ظ‚ط§طھ ط§ظ„ظˆط¸ظٹظپظٹط©", navGroupOrder: 8, navItemOrder: 3 },
  hr_termination: { navGroupKey: "hr_termination", navGroupLabel: "ط¥ظ†ظ‡ط§ط، ط§ظ„ط®ط¯ظ…ط©", navGroupOrder: 9, navItemOrder: 1 },
  hr_reports: { navGroupKey: "hr_reports", navGroupLabel: "ط§ظ„طھظ‚ط§ط±ظٹط±", navGroupOrder: 10, navItemOrder: 1 },
  hr_settings: { navGroupKey: "hr_settings", navGroupLabel: "ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ ظˆط§ظ„طµظ„ط§ط­ظٹط§طھ", navGroupOrder: 11, navItemOrder: 1 },
  employee_app_settings: { navGroupKey: "hr_settings", navGroupLabel: "ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ ظˆط§ظ„طµظ„ط§ط­ظٹط§طھ", navGroupOrder: 11, navItemOrder: 2 },
  users_permissions: { navGroupKey: "hr_settings", navGroupLabel: "ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ ظˆط§ظ„طµظ„ط§ط­ظٹط§طھ", navGroupOrder: 11, navItemOrder: 3 },

  inventory: { navGroupKey: "inventory_dashboard", navGroupLabel: "ظ„ظˆط­ط© ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 1, navItemOrder: 1, navLabel: "ظ„ظˆط­ط© ط§ظ„ظ…ط®ط²ظˆظ†" },
  inventory_items: { navGroupKey: "inventory_items", navGroupLabel: "ط§ظ„ط£طµظ†ط§ظپ", navGroupOrder: 2, navItemOrder: 1 },
  inventory_items_import_export: { navGroupKey: "inventory_items", navGroupLabel: "ط§ظ„ط£طµظ†ط§ظپ", navGroupOrder: 2, navItemOrder: 2 },
  inventory_categories: { navGroupKey: "inventory_classification", navGroupLabel: "ط§ظ„طھطµظ†ظٹظپط§طھ ظˆط§ظ„ظˆط­ط¯ط§طھ", navGroupOrder: 3, navItemOrder: 1 },
  inventory_units: { navGroupKey: "inventory_classification", navGroupLabel: "ط§ظ„طھطµظ†ظٹظپط§طھ ظˆط§ظ„ظˆط­ط¯ط§طھ", navGroupOrder: 3, navItemOrder: 2 },
  inventory_warehouses: { navGroupKey: "inventory_warehouses", navGroupLabel: "ط§ظ„ظ…ط³طھظˆط¯ط¹ط§طھ", navGroupOrder: 4, navItemOrder: 1 },
  inventory_suppliers: { navGroupKey: "inventory_purchasing", navGroupLabel: "ط§ظ„ظ…ط´طھط±ظٹط§طھ", navGroupOrder: 5, navItemOrder: 1 },
  inventory_purchase_requests: { navGroupKey: "inventory_purchasing", navGroupLabel: "ط§ظ„ظ…ط´طھط±ظٹط§طھ", navGroupOrder: 5, navItemOrder: 2 },
  inventory_purchase_orders: { navGroupKey: "inventory_purchasing", navGroupLabel: "ط§ظ„ظ…ط´طھط±ظٹط§طھ", navGroupOrder: 5, navItemOrder: 3 },
  inventory_receipts: { navGroupKey: "inventory_purchasing", navGroupLabel: "ط§ظ„ظ…ط´طھط±ظٹط§طھ", navGroupOrder: 5, navItemOrder: 4 },
  inventory_purchase_invoices: { navGroupKey: "inventory_purchasing", navGroupLabel: "ط§ظ„ظ…ط´طھط±ظٹط§طھ", navGroupOrder: 5, navItemOrder: 5 },
  inventory_issue_vouchers: { navGroupKey: "inventory_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 6, navItemOrder: 1 },
  inventory_returns: { navGroupKey: "inventory_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 6, navItemOrder: 2 },
  inventory_transfers: { navGroupKey: "inventory_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 6, navItemOrder: 3 },
  inventory_balances: { navGroupKey: "inventory_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 6, navItemOrder: 4 },
  inventory_movements: { navGroupKey: "inventory_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 6, navItemOrder: 5 },
  inventory_adjustments: { navGroupKey: "inventory_stocktake", navGroupLabel: "ط§ظ„ط¬ط±ط¯ ظˆط§ظ„طھط³ظˆظٹط§طھ", navGroupOrder: 7, navItemOrder: 1 },
  inventory_stocktakes: { navGroupKey: "inventory_stocktake", navGroupLabel: "ط§ظ„ط¬ط±ط¯ ظˆط§ظ„طھط³ظˆظٹط§طھ", navGroupOrder: 7, navItemOrder: 2 },
  inventory_alerts: { navGroupKey: "inventory_alerts", navGroupLabel: "ط§ظ„طھظ†ط¨ظٹظ‡ط§طھ", navGroupOrder: 8, navItemOrder: 1 },
  inventory_reports: { navGroupKey: "inventory_reports", navGroupLabel: "ط§ظ„طھظ‚ط§ط±ظٹط±", navGroupOrder: 9, navItemOrder: 1 },
  inventory_settings: { navGroupKey: "inventory_settings", navGroupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", navGroupOrder: 10, navItemOrder: 1 },

  assets_1: { navGroupKey: "assets_dashboard", navGroupLabel: "ظ„ظˆط­ط© ط§ظ„ط£طµظˆظ„", navGroupOrder: 1, navItemOrder: 1 },
  assets_2: { navGroupKey: "assets_registry", navGroupLabel: "ط³ط¬ظ„ ط§ظ„ط£طµظˆظ„", navGroupOrder: 2, navItemOrder: 1 },
  assets_3: { navGroupKey: "assets_setup", navGroupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ط£طµظˆظ„", navGroupOrder: 3, navItemOrder: 1 },
  assets_4: { navGroupKey: "assets_custodies", navGroupLabel: "ط§ظ„ط¹ظ‡ط¯", navGroupOrder: 4, navItemOrder: 1 },
  assets_5: { navGroupKey: "assets_finance", navGroupLabel: "ط§ظ„ط¥ظ‡ظ„ط§ظƒ ظˆط§ظ„ظ‚ظٹظ…ط©", navGroupOrder: 5, navItemOrder: 1 },
  assets_depreciation_tools: { navGroupKey: "assets_finance", navGroupLabel: "ط§ظ„ط¥ظ‡ظ„ط§ظƒ ظˆط§ظ„ظ‚ظٹظ…ط©", navGroupOrder: 5, navItemOrder: 2 },
  assets_6: { navGroupKey: "assets_maintenance", navGroupLabel: "ط§ظ„طµظٹط§ظ†ط©", navGroupOrder: 6, navItemOrder: 1 },
  assets_7: { navGroupKey: "assets_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ط£طµظˆظ„", navGroupOrder: 7, navItemOrder: 1 },
  assets_8: { navGroupKey: "assets_movements", navGroupLabel: "ط­ط±ظƒط§طھ ط§ظ„ط£طµظˆظ„", navGroupOrder: 7, navItemOrder: 2 },
  assets_9: { navGroupKey: "assets_reports", navGroupLabel: "طھظ‚ط§ط±ظٹط± ط§ظ„ط£طµظˆظ„", navGroupOrder: 8, navItemOrder: 1 },
  assets_import_export: { navGroupKey: "assets_reports", navGroupLabel: "طھظ‚ط§ط±ظٹط± ط§ظ„ط£طµظˆظ„", navGroupOrder: 8, navItemOrder: 2 },

  sales_1: { navGroupKey: "sales_dashboard", navGroupLabel: "ظ„ظˆط­ط© ط§ظ„ظ…ط¨ظٹط¹ط§طھ", navGroupOrder: 1, navItemOrder: 1 },
  sales_2: { navGroupKey: "sales_customers", navGroupLabel: "ط§ظ„ط¹ظ…ظ„ط§ط،", navGroupOrder: 2, navItemOrder: 1 },
  sales_3: { navGroupKey: "sales_quotes", navGroupLabel: "ط¹ط±ظˆط¶ ط§ظ„ط£ط³ط¹ط§ط±", navGroupOrder: 3, navItemOrder: 1 },
  sales_4: { navGroupKey: "sales_orders", navGroupLabel: "ط£ظˆط§ظ…ط± ط§ظ„ط¨ظٹط¹", navGroupOrder: 4, navItemOrder: 1 },
  sales_5: { navGroupKey: "sales_invoices", navGroupLabel: "ظپظˆط§طھظٹط± ط§ظ„ظ…ط¨ظٹط¹ط§طھ", navGroupOrder: 5, navItemOrder: 1 },
  sales_6: { navGroupKey: "sales_returns", navGroupLabel: "ط§ظ„ظ…ط±طھط¬ط¹ط§طھ", navGroupOrder: 6, navItemOrder: 1 },
  sales_7: { navGroupKey: "sales_collections", navGroupLabel: "ط§ظ„طھط­طµظٹظ„ط§طھ", navGroupOrder: 7, navItemOrder: 1 },
  sales_8: { navGroupKey: "sales_reports", navGroupLabel: "ط§ظ„طھظ‚ط§ط±ظٹط±", navGroupOrder: 9, navItemOrder: 1 },
};

const erpRegistryPages = [
  ["inventory_items", "ط§ظ„ط£طµظ†ط§ظپ", "inventory", "inventory", "inventory.items", commonActions, "active"],
  ["inventory_items_import_export", "ط§ط³طھظٹط±ط§ط¯ ظˆطھطµط¯ظٹط± ط§ظ„ط£طµظ†ط§ظپ", "inventory", "inventory_items_import_export", "inventory.items.import_export", ["can_view", "can_import", "can_export", "can_print"], "active"],
  ["inventory_suppliers", "ط§ظ„ظ…ظˆط±ط¯ظˆظ†", "inventory", "inventory", "inventory.suppliers", commonActions, "active"],
  ["inventory_purchase_requests", "ط·ظ„ط¨ط§طھ ط§ظ„ط´ط±ط§ط،", "inventory", "inventory", "inventory.purchase_requests", approvalActions, "active"],
  ["inventory_purchase_orders", "ط£ظˆط§ظ…ط± ط§ظ„ط´ط±ط§ط،", "inventory", "inventory", "inventory.purchase_orders", approvalActions, "active"],
  ["inventory_receipts", "ط§ظ„ط§ط³طھظ„ط§ظ…", "inventory", "inventory", "inventory.receipts", ["can_view", "can_create", "can_edit", "can_post", "can_export", "can_print"], "active"],
  ["inventory_issue_vouchers", "ط§ظ„طµط±ظپ", "inventory", "inventory", "inventory.issue_vouchers", approvalActions, "active"],
  ["inventory_transfers", "ط§ظ„طھط­ظˆظٹظ„ ط§ظ„ظ…ط®ط²ظ†ظٹ", "inventory", "inventory", "inventory.transfers", approvalActions, "active"],
  ["inventory_returns", "ط§ظ„ط¥ط±ط¬ط§ط¹", "inventory", "inventory", "inventory.returns", ["can_view", "can_create", "can_edit", "can_post", "can_export", "can_print"], "active"],
  ["inventory_adjustments", "ط§ظ„طھط³ظˆظٹط§طھ", "inventory", "inventory", "inventory.adjustments", approvalActions, "active"],
  ["inventory_stocktakes", "ط§ظ„ط¬ط±ط¯", "inventory", "inventory", "inventory.stocktakes", approvalActions, "active"],
  ["inventory_balances", "ط§ظ„ط£ط±طµط¯ط©", "inventory", "inventory", "inventory.balances", reportActions, "active"],
  ["inventory_movements", "ط­ط±ظƒط© ط§ظ„ظ…ط®ط²ظˆظ†", "inventory", "inventory", "inventory.movements", reportActions, "active"],
  ["inventory_reports", "طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط®ط²ظˆظ†", "inventory", "inventory", "inventory.reports", reportActions, "active"],
  ["inventory_settings", "ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ط®ط²ظˆظ†", "inventory", "inventory", "inventory.settings", settingsActions, "active"],
  ...["ظ„ظˆط­ط© ط§ظ„ظ…ط¨ظٹط¹ط§طھ", "ط§ظ„ط¹ظ…ظ„ط§ط،", "ط¹ط±ظˆط¶ ط§ظ„ط£ط³ط¹ط§ط±", "ط£ظˆط§ظ…ط± ط§ظ„ط¨ظٹط¹", "ظپظˆط§طھظٹط± ط§ظ„ط¨ظٹط¹", "ظ…ط±ط¯ظˆط¯ط§طھ ط§ظ„ط¨ظٹط¹", "ط§ظ„ظ…ط¯ظپظˆط¹ط§طھ", "طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط¨ظٹط¹ط§طھ"].map((label, index) => [`sales_${index + 1}`, label, "sales", `sales_${index + 1}`, `sales.page_${index + 1}`, index === 7 ? reportActions : commonActions, "placeholder"]),
  ...["ظ„ظˆط­ط© ط§ظ„ظ…ط´طھط±ظٹط§طھ", "ط§ظ„ظ…ظˆط±ط¯ظˆظ†", "ط·ظ„ط¨ط§طھ ط§ظ„ط´ط±ط§ط،", "ط£ظˆط§ظ…ط± ط§ظ„ط´ط±ط§ط،", "ظپظˆط§طھظٹط± ط§ظ„ط´ط±ط§ط،", "ظ…ط±ط¯ظˆط¯ط§طھ ط§ظ„ط´ط±ط§ط،", "ظ…ط¯ظپظˆط¹ط§طھ ط§ظ„ظ…ظˆط±ط¯ظٹظ†", "طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط´طھط±ظٹط§طھ"].map((label, index) => [`purchasing_${index + 1}`, label, "purchasing", index > 0 && index < 6 ? "inventory" : `purchasing_${index + 1}`, `purchasing.page_${index + 1}`, [2, 3].includes(index) ? approvalActions : index === 7 ? reportActions : commonActions, index > 0 && index < 6 ? "active" : "placeholder"]),
  ...["ظ„ظˆط­ط© ط§ظ„ط­ط³ط§ط¨ط§طھ", "ط¯ظ„ظٹظ„ ط§ظ„ط­ط³ط§ط¨ط§طھ", "ط§ظ„ظ‚ظٹظˆط¯ ط§ظ„ظٹظˆظ…ظٹط©", "ط³ظ†ط¯ ظ‚ط¨ط¶", "ط³ظ†ط¯ طµط±ظپ", "ظ…ط±ط§ظƒط² ط§ظ„طھظƒظ„ظپط©", "ط§ظ„ط¹ظ…ظ„ط§طھ", "ط§ظ„طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط§ظ„ظٹط©", "ظ…ظٹط²ط§ظ† ط§ظ„ظ…ط±ط§ط¬ط¹ط©", "ظ‚ط§ط¦ظ…ط© ط§ظ„ط¯ط®ظ„", "ط§ظ„ظ…ط±ظƒط² ط§ظ„ظ…ط§ظ„ظٹ", "ظƒط´ظپ ط­ط³ط§ط¨"].map((label, index) => [`accounting_${index + 1}`, label, "accounting", `accounting_${index + 1}`, `accounting.page_${index + 1}`, index >= 7 ? reportActions : financialActions, "placeholder"]),
  ...["ظ„ظˆط­ط© CRM", "ط§ظ„ط¹ظ…ظ„ط§ط، ط§ظ„ظ…ط­طھظ…ظ„ظˆظ†", "ط§ظ„ط¹ظ…ظ„ط§ط،", "ط§ظ„ظپط±طµ ط§ظ„ط¨ظٹط¹ظٹط©", "ط§ظ„ظ…طھط§ط¨ط¹ط§طھ", "ط§ظ„طھط°ط§ظƒط± ظˆط§ظ„ط´ظƒط§ظˆظ‰", "ط§ظ„ط­ظ…ظ„ط§طھ", "طھظ‚ط§ط±ظٹط± CRM"].map((label, index) => [`crm_${index + 1}`, label, "crm", `crm_${index + 1}`, `crm.page_${index + 1}`, index === 7 ? reportActions : commonActions, "placeholder"]),
  ...[
    ["assets_1", "ظ„ظˆط­ط© ط§ظ„ط£طµظˆظ„", "assets.dashboard", reportActions],
    ["assets_2", "ط³ط¬ظ„ ط§ظ„ط£طµظˆظ„", "assets.registry", ["can_view", "can_create", "can_edit", "can_delete", "can_import", "can_export", "can_print", "can_manage", "can_view_financial"]],
    ["assets_3", "طھطµظ†ظٹظپط§طھ ط§ظ„ط£طµظˆظ„", "assets.categories", settingsActions],
    ["assets_4", "ط§ظ„ط¹ظ‡ط¯", "assets.custodies", approvalActions],
    ["assets_5", "ط§ظ„ط¥ظ‡ظ„ط§ظƒ", "assets.depreciation", financialActions],
    ["assets_depreciation_tools", "ط­ط§ط³ط¨ط© ظˆط¬ط¯ظˆظ„ ط§ظ„ط¥ظ‡ظ„ط§ظƒ", "assets.depreciation.calculate", ["can_view", "can_export", "can_print", "can_manage"]],
    ["assets_6", "ط§ظ„طµظٹط§ظ†ط©", "assets.maintenance", approvalActions],
    ["assets_7", "ظ†ظ‚ظ„ ط§ظ„ط£طµظˆظ„", "assets.transfers", approvalActions],
    ["assets_8", "ط§ط³طھط¨ط¹ط§ط¯ ط§ظ„ط£طµظˆظ„", "assets.disposals", approvalActions],
    ["assets_9", "طھظ‚ط§ط±ظٹط± ط§ظ„ط£طµظˆظ„", "assets.reports", reportActions],
    ["assets_import_export", "ط§ط³طھظٹط±ط§ط¯ ظˆطھطµط¯ظٹط± ط§ظ„ط£طµظˆظ„", "assets.import_export", ["can_view", "can_import", "can_export", "can_print"]],
  ].map(([key, label, permissionKey, actions]) => [key, label, "assets", key, permissionKey, actions, "active"]),
  ...["ظ„ظˆط­ط© ط§ظ„ظ…ط´ط§ط±ظٹط¹", "ظ‚ط§ط¦ظ…ط© ط§ظ„ظ…ط´ط§ط±ظٹط¹", "ط§ظ„ظ…ظ‡ط§ظ…", "ط§ظ„ظپط±ظ‚", "ط§ظ„ظ…طµط±ظˆظپط§طھ", "ط§ظ„ظ…ط±ط§ط­ظ„", "ط§ظ„ظ…ط³طھظ†ط¯ط§طھ", "طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط´ط§ط±ظٹط¹"].map((label, index) => [`projects_${index + 1}`, label, "projects", `projects_${index + 1}`, `projects.page_${index + 1}`, index === 7 ? reportActions : commonActions, "placeholder"]),
].map(([key, label, moduleKey, routeKey, permissionKey, actions, status], index) => ({
  key,
  label,
  aliases: [],
  icon: "BriefcaseBusiness",
  group: moduleKey,
  groupLabel: erpModuleLabels[moduleKey] || moduleKey,
  permissionKey,
  moduleKey,
  moduleLabel: erpModuleLabels[moduleKey] || moduleKey,
  routeKey,
  order: 300 + index,
  actions,
  status,
  isOfficialPage: status !== "placeholder",
  isDuplicateAllowed: false,
  defaultEnabled: ["hr", "inventory", "purchasing"].includes(moduleKey) || status === "active",
}));

export const pageRegistry = [
  { key: "dashboard", label: "ط§ظ„ط±ط¦ظٹط³ظٹط©", aliases: ["ظ„ظˆط­ط© ط§ظ„طھط­ظƒظ…", "ط§ظ„ط¯ط§ط´ط¨ظˆط±ط¯"], icon: "LayoutDashboard", group: "core", groupLabel: "ط£ط³ط§ط³ظٹط©", permissionKey: "dashboard", moduleKey: "dashboard", order: 1, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "employees", label: "ظ‚ط§ط¦ظ…ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", aliases: ["ط§ظ„ظ…ظˆط¸ظپظˆظ†", "ط³ط¬ظ„ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "Users", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "employees", moduleKey: "employees", order: 2, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "employees_grid", label: "ظ‚ط§ط¦ظ…ط© ط§ظ„ظ…ظˆط¸ظپظٹظ† ط´ط¨ظƒظٹ", aliases: ["ط¨ط·ط§ظ‚ط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "Users", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "employees_grid", moduleKey: "employees_grid", order: 2.1, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "employee_effectiveness", label: "ط§ظ„ظ…ظˆط¸ظپظˆظ† ط§ظ„ظ…طھط¹ط§ظˆظ†ظˆظ† ظˆط؛ظٹط± ط§ظ„ظپط¹ط§ظ„ظˆظ†", aliases: ["ظپط¹ط§ظ„ظٹط© ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "UserCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "employee_effectiveness", moduleKey: "employee_effectiveness", order: 2.2, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "user_activity_logs", label: "ط³ط¬ظ„ط§طھ ط§ظ„ظ…ط³طھط®ط¯ظ…ظٹظ†", aliases: ["ظ†ط´ط§ط· ط§ظ„ظ…ط³طھط®ط¯ظ…ظٹظ†"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "user_activity_logs", moduleKey: "user_activity_logs", order: 2.3, isOfficialPage: true, isDuplicateAllowed: false, defaultEnabled: false },
  { key: "templates", label: "ظ†ظ…ط§ط°ط¬ ط§ظ„طھظ‚ظٹظٹظ…", aliases: ["ط§ظ„ظ‚ظˆط§ظ„ط¨ ط§ظ„ظ‚ط¯ظٹظ…ط©"], icon: "ClipboardList", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "templates", moduleKey: "templates", order: 3, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "evaluations", label: "طھظ‚ظٹظٹظ… ط§ظ„ظ…ظˆط¸ظپظٹظ†", aliases: ["طھظ‚ظٹظٹظ… ط£ط¯ط§ط، ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "BadgeCheck", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "employee_evaluation", moduleKey: "employee_evaluation", order: 4, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "productivity", label: "ط§ظ„ط¥ظ†طھط§ط¬ظٹط©", aliases: ["ظ…ط¤ط´ط±ط§طھ ط§ظ„ط¥ظ†طھط§ط¬ظٹط©"], icon: "Gauge", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "productivity", moduleKey: "productivity", order: 5, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "discipline", label: "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط§ظ†طµط±ط§ظپ", aliases: ["ط§ظ„ط§ظ†ط¶ط¨ط§ط· ط§ظ„ظˆط¸ظٹظپظٹ", "ط§ظ„ط­ط¶ظˆط±", "ط§ظ„ط§ظ†ط¶ط¨ط§ط·"], icon: "CalendarCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "discipline", moduleKey: "discipline", order: 6, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "incentives", label: "ط§ظ„ط­ظˆط§ظپط²", aliases: ["ط§ظ„ظ…ظƒط§ظپط¢طھ"], icon: "Gift", group: "financial", groupLabel: "ظ…ط§ظ„ظٹط©", permissionKey: "incentives", moduleKey: "incentives", order: 7, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "top", label: "ظ…ظˆط¸ظپ ط§ظ„ط´ظ‡ط±", aliases: ["ط£ظپط¶ظ„ ظ…ظˆط¸ظپ"], icon: "Trophy", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "employee_of_month", moduleKey: "employee_of_month", order: 8, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "plans", label: "ط®ط·ط· ط§ظ„طھط­ط³ظٹظ†", aliases: ["PIP", "ط®ط·ط© طھط­ط³ظٹظ† ط§ظ„ط£ط¯ط§ط،"], icon: "TrendingUp", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "improvement_plans", moduleKey: "improvement_plans", order: 9, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "reports", label: "ظ‚ط³ظ… ط§ظ„طھظ‚ط§ط±ظٹط±", aliases: ["ط§ظ„طھظ‚ط§ط±ظٹط±"], icon: "FileBarChart", group: "reports", groupLabel: "طھظ‚ط§ط±ظٹط±", permissionKey: "reports", moduleKey: "reports", order: 10, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "settings", label: "ط¥ط¹ط¯ط§ط¯ط§طھ", aliases: ["ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ†ط¸ط§ظ…"], icon: "Settings", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "settings", moduleKey: "settings", order: 11, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "guarantees", label: "ط¶ظ…ط§ظ†ط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†", aliases: ["ط§ظ„ط¶ظ…ط§ظ†ط§طھ"], icon: "ShieldCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "guarantees", moduleKey: "guarantees", order: 12, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "overtime", label: "ط§ظ„ط¹ظ…ظ„ ط§ظ„ط¥ط¶ط§ظپظٹ", aliases: ["ط³ط§ط¹ط§طھ ط¥ط¶ط§ظپظٹط©"], icon: "Clock3", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "overtime", moduleKey: "overtime", order: 13, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "overtime_import_export", label: "ط§ط³طھظٹط±ط§ط¯ ظˆطھطµط¯ظٹط± ط§ظ„ط¹ظ…ظ„ ط§ظ„ط¥ط¶ط§ظپظٹ", aliases: ["ط§ط³طھظٹط±ط§ط¯ ط§ظ„ط¯ظˆط§ظ… ط§ظ„ط¥ط¶ط§ظپظٹ"], icon: "FileSpreadsheet", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "hr.overtime.import_export", moduleKey: "overtime_import_export", order: 13.5, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "shifts", label: "ط´ظپطھط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†", aliases: ["ط§ظ„ط´ظپطھط§طھ", "ط§ظ„ط¬ط¯ط§ظˆظ„"], icon: "CalendarCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "shifts", moduleKey: "shifts", order: 14, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "inventory", label: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ط®ط²ظˆظ†", aliases: ["ط§ظ„ظ…ط®ط²ظˆظ†"], icon: "Wallet", group: "inventory", groupLabel: "ظ…ط®ط²ظˆظ†", permissionKey: "inventory", moduleKey: "inventory", order: 15, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "daily_operations", label: "ط§ظ„ط¹ظ…ظ„ظٹط§طھ ط§ظ„ظٹظˆظ…ظٹط©", aliases: ["ط¹ظ…ظ„ظٹط§طھ ظٹظˆظ…ظٹط©"], icon: "Gauge", group: "core", groupLabel: "ط£ط³ط§ط³ظٹط©", permissionKey: "daily_operations", moduleKey: "daily_operations", order: 16, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "daily_operations_reports", label: "طھظ‚ط§ط±ظٹط± ط§ظ„ط¹ظ…ظ„ظٹط§طھ ط§ظ„ظٹظˆظ…ظٹط©", aliases: ["طھظ‚ط±ظٹط± ط§ظ„ط¹ظ…ظ„ظٹط§طھ ط§ظ„ظٹظˆظ…ظٹط©"], icon: "FileBarChart", group: "core", groupLabel: "ط£ط³ط§ط³ظٹط©", permissionKey: "hr.daily_operations.reports.view", moduleKey: "daily_operations_reports", order: 16.5, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "performance_criteria", label: "ظ…ط¹ط§ظٹظٹط± ط§ظ„ط£ط¯ط§ط،", aliases: ["ظ…ط¹ط§ظٹظٹط± ط§ظ„طھظ‚ظٹظٹظ…"], icon: "ClipboardList", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "performance_standards", moduleKey: "performance_standards", order: 17, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "performance-monthly-targets", label: "أهداف الشهر", icon: "Target", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-monthly-targets", moduleKey: "hr", order: 17.2, isOfficialPage: true, defaultEnabled: true },
  { key: "performance-branch-targets", label: "أهداف الفروع", icon: "Building2", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-branch-targets", moduleKey: "hr", order: 17.3, isOfficialPage: true, defaultEnabled: true },
  { key: "performance-attendance-rules", label: "قواعد الحضور والانضباط", icon: "CalendarCheck", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-attendance-rules", moduleKey: "hr", order: 17.4, isOfficialPage: true, defaultEnabled: true },
  { key: "performance-incentive-exclusions", label: "استثناءات الحوافز", icon: "Ban", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-incentive-exclusions", moduleKey: "hr", order: 18.8, isOfficialPage: true, defaultEnabled: true },
  { key: "performance-incentive-proposal", label: "تصور نظام الحوافز", aliases: ["تصور نظام التقييم والحوافز"], icon: "FileText", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-incentive-proposal", moduleKey: "hr", order: 18.85, isOfficialPage: true, defaultEnabled: true },
  { key: "performance-process-guide", label: "شرح آلية التقييم والحوافز", icon: "BookOpen", group: "performance", groupLabel: "الأداء والحوافز", permissionKey: "performance-process-guide", moduleKey: "hr", order: 18.9, isOfficialPage: true, defaultEnabled: true },
  { key: "performance_kpi_scores", label: "ط¯ط±ط¬ط§طھ KPI", aliases: ["ظ†طھط§ط¦ط¬ KPI"], icon: "Star", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "kpi_scores", moduleKey: "kpi_scores", order: 18, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "kpi_settings", label: "ط¥ط¹ط¯ط§ط¯ط§طھ KPI", aliases: ["ط¥ط¹ط¯ط§ط¯ط§طھ ظ…ط¤ط´ط±ط§طھ ط§ظ„ط£ط¯ط§ط،"], icon: "Settings", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "kpi_settings", moduleKey: "hr", order: 18.5, isOfficialPage: true, isDuplicateAllowed: false, status: "active", defaultEnabled: true },
  { key: "users_permissions", label: "ط§ظ„ظ…ط³طھط®ط¯ظ…ظˆظ† ظˆط§ظ„طµظ„ط§ط­ظٹط§طھ", aliases: ["ط§ظ„طµظ„ط§ط­ظٹط§طھ", "ط§ظ„ط£ط¯ظˆط§ط±"], icon: "UserRoundCog", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "users_permissions", moduleKey: "users_permissions", order: 19, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "recruitment", label: "ط·ظ„ط¨ط§طھ ط§ظ„طھظˆط¸ظٹظپ", aliases: ["ط§ظ„طھظˆط¸ظٹظپ"], icon: "UserPlus", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "recruitment_requests", moduleKey: "recruitment_requests", order: 20, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "reports_center", label: "ظ…ط±ظƒط² ط§ظ„طھظ‚ط§ط±ظٹط±", aliases: ["ط§ظ„طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ط±ظƒط²ظٹط©"], icon: "FileBarChart", group: "reports", groupLabel: "طھظ‚ط§ط±ظٹط±", permissionKey: "report_center", moduleKey: "report_center", order: 21, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "audit_logs", label: "ط³ط¬ظ„ ط§ظ„ط¹ظ…ظ„ظٹط§طھ", aliases: ["ط³ط¬ظ„ ط§ظ„طھط¯ظ‚ظٹظ‚"], icon: "ClipboardList", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "audit_logs", moduleKey: "audit_logs", order: 22, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "companies_admin", label: "ط¥ط¯ط§ط±ط© ط§ظ„ط´ط±ظƒط§طھ", aliases: ["ط´ط±ظƒط§طھ ط§ظ„ظ…ظ†طµط©"], icon: "Building2", group: "platform", groupLabel: "ظ…ظ†طµط©", permissionKey: "companies_management", moduleKey: "companies_management", order: 23, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "system_settings", label: "ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ط¹ط§ظ…ط©", aliases: ["ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ†ط¸ط§ظ… ط§ظ„ط¹ط§ظ…ط©"], icon: "Settings", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "system.settings", moduleKey: "system", moduleLabel: "ط§ظ„ظ†ط¸ط§ظ…", routeKey: "system_settings", order: 24, isOfficialPage: true, isDuplicateAllowed: false, status: "active", defaultEnabled: true },
  { key: "hr_home", label: "ط§ظ„ط±ط¦ظٹط³ظٹط©", aliases: ["ط±ط¦ظٹط³ظٹط© ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©"], icon: "LayoutDashboard", group: "core", groupLabel: "ط£ط³ط§ط³ظٹط©", permissionKey: "hr_home", moduleKey: "hr_home", order: 101, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_requests_approvals", label: "ط§ظ„ط·ظ„ط¨ط§طھ ظˆط§ظ„ظ…ظˆط§ظپظ‚ط§طھ", aliases: ["ط·ظ„ط¨ط§طھ ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©", "ط§ظ„ظ…ظˆط§ظپظ‚ط§طھ"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "hr.requests_approvals", moduleKey: "hr_requests_approvals", order: 106, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_reports", label: "طھظ‚ط§ط±ظٹط± ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©", aliases: ["طھظ‚ط§ط±ظٹط± HR"], icon: "FileBarChart", group: "reports", groupLabel: "طھظ‚ط§ط±ظٹط±", permissionKey: "hr.reports", moduleKey: "hr_reports", order: 122, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_settings", label: "ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©", aliases: ["ط¥ط¹ط¯ط§ط¯ط§طھ HR"], icon: "Settings", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "hr.settings", moduleKey: "hr_settings", order: 123, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "employee_app_settings", label: "ط¥ط¹ط¯ط§ط¯ط§طھ طھط·ط¨ظٹظ‚ ط§ظ„ظ…ظˆط¸ظپ", aliases: ["ط¨ظˆط§ط¨ط© ط§ظ„ظ…ظˆط¸ظپ", "طھط·ط¨ظٹظ‚ ط§ظ„ظ…ظˆط¸ظپ"], icon: "Smartphone", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "employee_app_settings", moduleKey: "employee_app_settings", order: 123.5, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "hr_employees_full", label: "ظ‚ط§ط¦ظ…ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", aliases: ["ظ‚ط§ط¦ظ…ط© ظ…ظˆط¸ظپظٹظ† ظƒط§ظ…ظ„ط©"], icon: "Users", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "hr_employees_full", moduleKey: "hr_employees_full", order: 102, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_reports_full", label: "ظ‚ط³ظ… ط§ظ„طھظ‚ط§ط±ظٹط±", aliases: ["ظ‚ط³ظ… طھظ‚ط§ط±ظٹط± ظƒط§ظ…ظ„"], icon: "FileBarChart", group: "reports", groupLabel: "طھظ‚ط§ط±ظٹط±", permissionKey: "hr_reports_full", moduleKey: "hr_reports_full", order: 103, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_requests", label: "ط§ظ„ط·ظ„ط¨ط§طھ", aliases: ["ط·ظ„ط¨ط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "requests", moduleKey: "requests", order: 104, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_performance_full", label: "ظ‚ظٹط§ط³ ط§ظ„ط£ط¯ط§ط،", aliases: ["ط£ط¯ط§ط، ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©"], icon: "BadgeCheck", group: "performance", groupLabel: "ط§ظ„ط£ط¯ط§ط،", permissionKey: "performance", moduleKey: "performance", order: 105, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_incentives_full", label: "ط§ظ„ط­ظˆط§ظپط²", aliases: ["ط­ظˆط§ظپط² ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©"], icon: "Gift", group: "financial", groupLabel: "ظ…ط§ظ„ظٹط©", permissionKey: "hr_incentives_full", moduleKey: "hr_incentives_full", order: 106, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_attendance_payroll", label: "ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", aliases: ["ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط¯ظˆط§ظ…"], icon: "Clock3", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance", moduleKey: "attendance", order: 107, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr-attendance-records", label: "الحضور والغياب", icon: "CalendarCheck", group: "hr", groupLabel: "الموارد البشرية", permissionKey: "hr-attendance-records", moduleKey: "hr", order: 106.5, isOfficialPage: true, isDuplicateAllowed: false, status: "active", defaultEnabled: true },
  { key: "attendance_dashboard", label: "ظ„ظˆط­ط© ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…", aliases: ["ط­ط³ط§ط¨ ط§ظ„ط¯ظˆط§ظ…"], icon: "Clock3", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance_dashboard", moduleKey: "attendance", order: 107, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "attendance_records", label: "طھط³ط¬ظٹظ„ ط­ط¶ظˆط± ظˆط§ظ†طµط±ط§ظپ", aliases: ["ط³ط¬ظ„ ط§ظ„ط­ط¶ظˆط±", "ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط§ظ†طµط±ط§ظپ"], icon: "CalendarCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance_records", moduleKey: "attendance", order: 108, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "bulk_attendance", label: "طھط­ط¶ظٹط± ط¬ظ…ط§ط¹ظٹ", aliases: ["ط§ظ„طھط­ط¶ظٹط± ط§ظ„ط¬ظ…ط§ط¹ظٹ"], icon: "Users", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "bulk_attendance", moduleKey: "attendance", order: 109, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "attendance_requests", label: "ظ…ط¹ط§ظ„ط¬ط© ط·ظ„ط¨ط§طھ ط§ظ„ط¹ظ…ظ„", aliases: ["ط·ظ„ط¨ط§طھ ط§ظ„ط­ط¶ظˆط±"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance_requests", moduleKey: "attendance", order: 110, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "working_hours_report", label: "طھظ‚ط±ظٹط± ط³ط§ط¹ط§طھ ط§ظ„ط§ط´طھط؛ط§ظ„", aliases: ["ط³ط§ط¹ط§طھ ط§ظ„ط¹ظ…ظ„"], icon: "FileBarChart", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "working_hours_report", moduleKey: "attendance", order: 111, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "attendance_in_out_report", label: "طھظ‚ط±ظٹط± ط§ظ„ط­ط¶ظˆط± ظˆط§ظ„ط§ظ†طµط±ط§ظپ", aliases: ["ط­ط±ظƒط© ط§ظ„ط­ط¶ظˆط±"], icon: "FileBarChart", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance_in_out_report", moduleKey: "attendance", order: 112, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "monthly_attendance_report", label: "طھظ‚ط±ظٹط± ط§ظ„ط­ط¶ظˆط± ط§ظ„ط´ظ‡ط±ظٹ", aliases: ["ظƒط´ظپ ط§ظ„ط­ط¶ظˆط± ط§ظ„ط´ظ‡ط±ظٹ"], icon: "CalendarDays", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "monthly_attendance_report", moduleKey: "attendance", order: 113, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "attendance_period_settings", label: "ط¥ط¹ط¯ط§ط¯ط§طھ ظپطھط±ط§طھ ط§ظ„ط¯ظˆط§ظ…", aliases: ["ظپطھط±ط§طھ ط§ظ„ط¯ظˆط§ظ…"], icon: "Settings", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "attendance_period_settings", moduleKey: "attendance", order: 114, isOfficialPage: true, isDuplicateAllowed: false, status: "active" },
  { key: "hr_salary", label: "ط­ط³ط§ط¨ ط§ظ„ط±ط§طھط¨", aliases: ["ط§ظ„ط±ظˆط§طھط¨"], icon: "Wallet", group: "financial", groupLabel: "ظ…ط§ظ„ظٹط©", permissionKey: "salaries", moduleKey: "salaries", order: 108, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_disciplinary", label: "ط§ظ„ظ…ط³ط§ط،ظ„ط§طھ ظˆط§ظ„ط¥ظ†ط°ط§ط±ط§طھ", aliases: ["ط§ظ„ظ…ط³ط§ط،ظ„ط§طھ"], icon: "AlertTriangle", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "disciplinary", moduleKey: "disciplinary", order: 109, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_recruitment_full", label: "ط§ظ„طھظˆط¸ظٹظپ", aliases: ["ط§ظ„طھظˆط¸ظٹظپ ط§ظ„ظƒط§ظ…ظ„"], icon: "UserPlus", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "recruitment", moduleKey: "recruitment", order: 110, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_leaves", label: "ط§ظ„ط¥ط¬ط§ط²ط§طھ", aliases: ["ط¥ط¯ط§ط±ط© ط§ظ„ط¥ط¬ط§ط²ط§طھ"], icon: "CalendarCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "leaves", moduleKey: "leaves", order: 111, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_complaints", label: "ط§ظ„ط´ظƒط§ظˆظ‰", aliases: ["ط´ظƒط§ظˆظ‰ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "MessageSquareWarning", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "complaints", moduleKey: "complaints", order: 112, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_circulars", label: "ط§ظ„طھط¹ط§ظ…ظٹظ…", aliases: ["ط§ظ„طھط¹ط§ظ…ظٹظ… ط§ظ„ط¥ط¯ط§ط±ظٹط©"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "circulars", moduleKey: "circulars", order: 113, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_termination", label: "ط¥ظ†ظ‡ط§ط، ط§ظ„ط®ط¯ظ…ط©", aliases: ["ظ†ظ‡ط§ظٹط© ط§ظ„ط®ط¯ظ…ط©"], icon: "LogOut", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "end_of_service", moduleKey: "end_of_service", order: 114, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_surveys", label: "ط§ظ„ط§ط³طھط¨ظٹط§ظ†ط§طھ", aliases: ["ط§ط³طھط¨ظٹط§ظ†ط§طھ"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "surveys", moduleKey: "surveys", order: 115, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_insurance", label: "ط§ظ„طھط£ظ…ظٹظ†ط§طھ", aliases: ["ط§ظ„طھط£ظ…ظٹظ†"], icon: "ShieldCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "insurance", moduleKey: "insurance", order: 116, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_announcements", label: "ظ‚ط³ظ… ط§ظ„ط¥ط¹ظ„ط§ظ†ط§طھ", aliases: ["ط§ظ„ط¥ط¹ظ„ط§ظ†ط§طھ"], icon: "Bell", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "announcements", moduleKey: "announcements", order: 117, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_files", label: "ط¥ط¯ط§ط±ط© ط§ظ„ظ…ظ„ظپط§طھ", aliases: ["ظ…ظ„ظپط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "FileSpreadsheet", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "files", moduleKey: "files", order: 118, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_contracts", label: "ط§ظ„ط¹ظ‚ظˆط¯", aliases: ["ط¹ظ‚ظˆط¯ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "ClipboardList", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "contracts", moduleKey: "contracts", order: 119, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_custodies", label: "ط§ظ„ط¹ظ‡ط¯", aliases: ["ط¹ظ‡ط¯ ط§ظ„ظ…ظˆط¸ظپظٹظ†"], icon: "Wallet", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "custodies", moduleKey: "custodies", order: 120, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_training", label: "ط§ظ„طھط¯ط±ظٹط¨", aliases: ["ط§ظ„طھط¯ط±ظٹط¨ ظˆط§ظ„طھط·ظˆظٹط±"], icon: "Star", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "training", moduleKey: "training", order: 121, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_approvals", label: "ط§ظ„ظ…ظˆط§ظپظ‚ط§طھ", aliases: ["ط§ظ„ط§ط¹طھظ…ط§ط¯ط§طھ"], icon: "BadgeCheck", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "approvals", moduleKey: "approvals", order: 122, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_org_chart", label: "ط§ظ„ظ‡ظٹظƒظ„ ط§ظ„طھظ†ط¸ظٹظ…ظٹ", aliases: ["ط§ظ„ظ‡ظٹظƒظ„"], icon: "Building2", group: "hr", groupLabel: "ظ…ظˆط§ط±ط¯ ط¨ط´ط±ظٹط©", permissionKey: "organization", moduleKey: "organization", order: 123, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "hr_settings_full", label: "ط¥ط¹ط¯ط§ط¯ط§طھ", aliases: ["ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©"], icon: "Settings", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "hr_settings_full", moduleKey: "hr_settings_full", order: 124, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_financial_setup", label: "طھظ‡ظٹط¦ط© ط§ظ„ظ…ط¹ظ„ظˆظ…ط§طھ ط§ظ„ظ…ط§ظ„ظٹط©", aliases: ["ط§ظ„ط¥ط¹ط¯ط§ط¯ ط§ظ„ظ…ط§ظ„ظٹ"], icon: "CircleDollarSign", group: "financial", groupLabel: "ظ…ط§ظ„ظٹط©", permissionKey: "financial_setup", moduleKey: "financial_setup", order: 125, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "hr_templates_full", label: "ط§ظ„ظ‚ظˆط§ظ„ط¨", aliases: ["ظ‚ظˆط§ظ„ط¨ ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©"], icon: "ClipboardList", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "hr_templates_full", moduleKey: "hr_templates_full", order: 126, isOfficialPage: false, isDuplicateAllowed: false, status: "alias", defaultEnabled: false },
  { key: "ai_assistant", label: "ط§ظ„ظ…ط³ط§ط¹ط¯ ط§ظ„ط°ظƒظٹ", aliases: ["AI"], icon: "UserRoundCog", group: "core", groupLabel: "ط£ط³ط§ط³ظٹط©", permissionKey: "ai_assistant", moduleKey: "ai_assistant", order: 125, isOfficialPage: true, isDuplicateAllowed: false },
  { key: "theme_settings", label: "ط§ظ„ط«ظٹظ… ظˆط§ظ„ط£ظ„ظˆط§ظ†", aliases: ["ط£ظ„ظˆط§ظ† ط§ظ„ط´ط±ظƒط©"], icon: "Settings", group: "settings", groupLabel: "ط¥ط¹ط¯ط§ط¯ط§طھ", permissionKey: "theme_settings", moduleKey: "theme_settings", order: 126, isOfficialPage: true, isDuplicateAllowed: false },
  ...erpRegistryPages,
].map((page) => {
  const normalizedModuleKey = moduleOverrides[page.key] || (hrPageKeys.has(page.key) ? "hr" : page.moduleKey || "hr");
  const navMetadata = navigationMetadata[page.key] || {};
  const isAlias = page.status === "alias";
  return {
  ...page,
  ...navMetadata,
  moduleKey: normalizedModuleKey,
  moduleLabel: page.moduleLabel || erpModuleLabels[normalizedModuleKey] || page.groupLabel || page.label,
  actions: page.actions || pageActionOverrides[page.key] || commonActions,
  status: page.status || "active",
  routeKey: page.routeKey || page.key,
  defaultEnabled: page.defaultEnabled ?? !["salaries", "financial_setup", "incentives", "inventory", "ai_assistant", "companies_management"].includes(page.permissionKey),
  canonical: !isAlias,
  alias: isAlias,
  hiddenFromNavigation: page.hiddenFromNavigation ?? isAlias,
  };
});

export const pageRegistryByKey = Object.fromEntries(pageRegistry.map((page) => [page.key, page]));
export const permissionKeyForPage = (pageKey = "") => pageRegistryByKey[pageKey]?.permissionKey || pageKey;

export const validateUniquePermissionKeys = (pages = pageRegistry) => {
  const seen = new Map();
  const duplicates = [];
  for (const page of pages || []) {
    if (!page?.permissionKey) continue;
    if (seen.has(page.permissionKey)) {
      duplicates.push({ permissionKey: page.permissionKey, firstPage: seen.get(page.permissionKey), duplicatePage: page.key });
    } else {
      seen.set(page.permissionKey, page.key);
    }
  }
  if (duplicates.length) console.warn("Duplicate permissionKey in pageRegistry:", duplicates);
  return duplicates;
};

validateUniquePermissionKeys(pageRegistry);

export const findPageByArabicName = (value = "") => {
  const text = String(value).trim().toLowerCase();
  if (!text) return null;
  return pageRegistry.find((page) =>
    [page.label, page.key, page.permissionKey, ...(page.aliases || [])].some((name) => text.includes(String(name).toLowerCase())),
  ) || null;
};

export const assistantModes = [
  {
    id: "navigation",
    label: "ظ…ط³ط§ط¹ط¯ ط§ظ„طھظ†ظ‚ظ„",
    prompts: ["ط§ظپطھط­ طµظپط­ط© ط¶ظ…ط§ظ†ط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†", "ط§ظپطھط­ طµظپط­ط© ط§ظ„ظ…ظˆط¸ظپظٹظ†", "ط§ظ†طھظ‚ظ„ ط¥ظ„ظ‰ ط§ظ„طھظ‚ط§ط±ظٹط±", "ط§ط°ظ‡ط¨ ط¥ظ„ظ‰ ط§ظ„ظ…ط®ط²ظˆظ†"],
  },
  {
    id: "reports",
    label: "ظ…ط³ط§ط¹ط¯ ط§ظ„طھظ‚ط§ط±ظٹط±",
    prompts: ["ط£ظ†ط´ط¦ طھظ‚ط±ظٹط± ط£ط¯ط§ط، ط´ظ‡ط±ظٹ", "ط£ظ†ط´ط¦ طھظ‚ط±ظٹط± ط¶ظ…ط§ظ†ط§طھ ط§ظ„ظ…ظˆط¸ظپظٹظ†", "ط£ظ†ط´ط¦ طھظ‚ط±ظٹط± ظ…ط®ط²ظˆظ†", "ط£ظ†ط´ط¦ طھظ‚ط±ظٹط± ط­ط¶ظˆط± ظˆط§ظ†ط¶ط¨ط§ط·"],
  },
  {
    id: "plans",
    label: "ظ…ط³ط§ط¹ط¯ ط§ظ„ط®ط·ط· ظˆط§ظ„ط§ط³طھط±ط§طھظٹط¬ظٹط§طھ",
    prompts: ["ط§ط¨ظ†ظٹ ط®ط·ط© ط§ط³طھط±ط§طھظٹط¬ظٹط© ظ„ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©", "ط§ط¨ظ†ظٹ ط®ط·ط© طھط´ط؛ظٹظ„ظٹط© ظ„طھط­ط³ظٹظ† ط§ظ„ظپط±ظˆط¹", "ط§ط¨ظ†ظٹ ط®ط·ط© طھط¯ط±ظٹط¨ ط´ظ‡ط±ظٹط©", "ط§ط¨ظ†ظٹ ط¨ط±ظ†ط§ظ…ط¬ طھط­ط³ظٹظ† ط£ط¯ط§ط،"],
  },
  {
    id: "hr",
    label: "ظ…ط³ط§ط¹ط¯ ط§ظ„ظ…ظˆط§ط±ط¯ ط§ظ„ط¨ط´ط±ظٹط©",
    prompts: ["ط­ظ„ظ„ ط£ط¯ط§ط، ط§ظ„ظ…ظˆط¸ظپظٹظ†", "ط§ظ‚طھط±ط­ ط®ط·ط© طھظ‚ظ„ظٹظ„ ط¯ظˆط±ط§ظ† ط§ظ„ظ…ظˆط¸ظپظٹظ†", "ط§ظƒطھط¨ ط®ط·ط© طھظˆط¸ظٹظپ", "ط§ظ‚طھط±ط­ ط¨ط±ظ†ط§ظ…ط¬ طھط£ظ‡ظٹظ„ ظ…ظˆط¸ظپ ط¬ط¯ظٹط¯"],
  },
];
